/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AssemblerConfigApplyConfiguration represents a declarative configuration of the AssemblerConfig type for use
// with apply.
type AssemblerConfigApplyConfiguration struct {
	Host       *string                                `json:"host,omitempty"`
	Port       *int32                                 `json:"port,omitempty"`
	TLSCertRef *SecretKeyNSSelectorApplyConfiguration `json:"tlsCertRef,omitempty"`
}

// AssemblerConfigApplyConfiguration constructs a declarative configuration of the AssemblerConfig type for use with
// apply.
func AssemblerConfig() *AssemblerConfigApplyConfiguration {
	return &AssemblerConfigApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *AssemblerConfigApplyConfiguration) WithHost(value string) *AssemblerConfigApplyConfiguration {
	b.Host = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *AssemblerConfigApplyConfiguration) WithPort(value int32) *AssemblerConfigApplyConfiguration {
	b.Port = &value
	return b
}

// WithTLSCertRef sets the TLSCertRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSCertRef field is set to the value of the last call.
func (b *AssemblerConfigApplyConfiguration) WithTLSCertRef(value *SecretKeyNSSelectorApplyConfiguration) *AssemblerConfigApplyConfiguration {
	b.TLSCertRef = value
	return b
}
