/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// BatcherInstanceApplyConfiguration represents a declarative configuration of the BatcherInstance type for use
// with apply.
type BatcherInstanceApplyConfiguration struct {
	CommonComponentConfigApplyConfiguration `json:",inline"`
	ShardID                                 *int32                               `json:"shardID,omitempty"`
	Ingress                                 *IngressConfigApplyConfiguration     `json:"ingress,omitempty"`
	Certificates                            *CertificateConfigApplyConfiguration `json:"certificates,omitempty"`
	Endpoints                               []string                             `json:"endpoints,omitempty"`
	Env                                     []EnvVarApplyConfiguration           `json:"env,omitempty"`
	Command                                 []string                             `json:"command,omitempty"`
	Args                                    []string                             `json:"args,omitempty"`
}

// BatcherInstanceApplyConfiguration constructs a declarative configuration of the BatcherInstance type for use with
// apply.
func BatcherInstance() *BatcherInstanceApplyConfiguration {
	return &BatcherInstanceApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *BatcherInstanceApplyConfiguration) WithReplicas(value int32) *BatcherInstanceApplyConfiguration {
	b.CommonComponentConfigApplyConfiguration.Replicas = &value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *BatcherInstanceApplyConfiguration) WithStorage(value *StorageConfigApplyConfiguration) *BatcherInstanceApplyConfiguration {
	b.CommonComponentConfigApplyConfiguration.Storage = value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *BatcherInstanceApplyConfiguration) WithResources(value v1.ResourceRequirements) *BatcherInstanceApplyConfiguration {
	b.CommonComponentConfigApplyConfiguration.Resources = &value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *BatcherInstanceApplyConfiguration) WithSecurityContext(value *SecurityContextApplyConfiguration) *BatcherInstanceApplyConfiguration {
	b.CommonComponentConfigApplyConfiguration.SecurityContext = value
	return b
}

// WithPodAnnotations puts the entries into the PodAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodAnnotations field,
// overwriting an existing map entries in PodAnnotations field with the same key.
func (b *BatcherInstanceApplyConfiguration) WithPodAnnotations(entries map[string]string) *BatcherInstanceApplyConfiguration {
	if b.CommonComponentConfigApplyConfiguration.PodAnnotations == nil && len(entries) > 0 {
		b.CommonComponentConfigApplyConfiguration.PodAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.CommonComponentConfigApplyConfiguration.PodAnnotations[k] = v
	}
	return b
}

// WithPodLabels puts the entries into the PodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodLabels field,
// overwriting an existing map entries in PodLabels field with the same key.
func (b *BatcherInstanceApplyConfiguration) WithPodLabels(entries map[string]string) *BatcherInstanceApplyConfiguration {
	if b.CommonComponentConfigApplyConfiguration.PodLabels == nil && len(entries) > 0 {
		b.CommonComponentConfigApplyConfiguration.PodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.CommonComponentConfigApplyConfiguration.PodLabels[k] = v
	}
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *BatcherInstanceApplyConfiguration) WithVolumes(values ...*VolumeApplyConfiguration) *BatcherInstanceApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumes")
		}
		b.CommonComponentConfigApplyConfiguration.Volumes = append(b.CommonComponentConfigApplyConfiguration.Volumes, *values[i])
	}
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *BatcherInstanceApplyConfiguration) WithAffinity(value *AffinityApplyConfiguration) *BatcherInstanceApplyConfiguration {
	b.CommonComponentConfigApplyConfiguration.Affinity = value
	return b
}

// WithVolumeMounts adds the given value to the VolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeMounts field.
func (b *BatcherInstanceApplyConfiguration) WithVolumeMounts(values ...*VolumeMountApplyConfiguration) *BatcherInstanceApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumeMounts")
		}
		b.CommonComponentConfigApplyConfiguration.VolumeMounts = append(b.CommonComponentConfigApplyConfiguration.VolumeMounts, *values[i])
	}
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *BatcherInstanceApplyConfiguration) WithImagePullSecrets(values ...*ImagePullSecretApplyConfiguration) *BatcherInstanceApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithImagePullSecrets")
		}
		b.CommonComponentConfigApplyConfiguration.ImagePullSecrets = append(b.CommonComponentConfigApplyConfiguration.ImagePullSecrets, *values[i])
	}
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *BatcherInstanceApplyConfiguration) WithTolerations(values ...*TolerationApplyConfiguration) *BatcherInstanceApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTolerations")
		}
		b.CommonComponentConfigApplyConfiguration.Tolerations = append(b.CommonComponentConfigApplyConfiguration.Tolerations, *values[i])
	}
	return b
}

// WithShardID sets the ShardID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShardID field is set to the value of the last call.
func (b *BatcherInstanceApplyConfiguration) WithShardID(value int32) *BatcherInstanceApplyConfiguration {
	b.ShardID = &value
	return b
}

// WithIngress sets the Ingress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ingress field is set to the value of the last call.
func (b *BatcherInstanceApplyConfiguration) WithIngress(value *IngressConfigApplyConfiguration) *BatcherInstanceApplyConfiguration {
	b.Ingress = value
	return b
}

// WithCertificates sets the Certificates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Certificates field is set to the value of the last call.
func (b *BatcherInstanceApplyConfiguration) WithCertificates(value *CertificateConfigApplyConfiguration) *BatcherInstanceApplyConfiguration {
	b.Certificates = value
	return b
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *BatcherInstanceApplyConfiguration) WithEndpoints(values ...string) *BatcherInstanceApplyConfiguration {
	for i := range values {
		b.Endpoints = append(b.Endpoints, values[i])
	}
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *BatcherInstanceApplyConfiguration) WithEnv(values ...*EnvVarApplyConfiguration) *BatcherInstanceApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnv")
		}
		b.Env = append(b.Env, *values[i])
	}
	return b
}

// WithCommand adds the given value to the Command field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Command field.
func (b *BatcherInstanceApplyConfiguration) WithCommand(values ...string) *BatcherInstanceApplyConfiguration {
	for i := range values {
		b.Command = append(b.Command, values[i])
	}
	return b
}

// WithArgs adds the given value to the Args field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Args field.
func (b *BatcherInstanceApplyConfiguration) WithArgs(values ...string) *BatcherInstanceApplyConfiguration {
	for i := range values {
		b.Args = append(b.Args, values[i])
	}
	return b
}
