/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CAEnrollmentSpecApplyConfiguration represents a declarative configuration of the CAEnrollmentSpec type for use
// with apply.
type CAEnrollmentSpecApplyConfiguration struct {
	CAName           *string                                  `json:"caName,omitempty"`
	CANamespace      *string                                  `json:"caNamespace,omitempty"`
	EnrollID         *string                                  `json:"enrollID,omitempty"`
	EnrollSecretRef  *CAEnrollmentSecretRefApplyConfiguration `json:"enrollSecretRef,omitempty"`
	Type             *string                                  `json:"type,omitempty"`
	Affiliation      *string                                  `json:"affiliation,omitempty"`
	Attrs            []CAEnrollmentAttrApplyConfiguration     `json:"attrs,omitempty"`
	MaxEnrollments   *int                                     `json:"maxEnrollments,omitempty"`
	OutputSecretName *string                                  `json:"outputSecretName,omitempty"`
	TLS              *CAEnrollmentTLSApplyConfiguration       `json:"tls,omitempty"`
}

// CAEnrollmentSpecApplyConfiguration constructs a declarative configuration of the CAEnrollmentSpec type for use with
// apply.
func CAEnrollmentSpec() *CAEnrollmentSpecApplyConfiguration {
	return &CAEnrollmentSpecApplyConfiguration{}
}

// WithCAName sets the CAName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CAName field is set to the value of the last call.
func (b *CAEnrollmentSpecApplyConfiguration) WithCAName(value string) *CAEnrollmentSpecApplyConfiguration {
	b.CAName = &value
	return b
}

// WithCANamespace sets the CANamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CANamespace field is set to the value of the last call.
func (b *CAEnrollmentSpecApplyConfiguration) WithCANamespace(value string) *CAEnrollmentSpecApplyConfiguration {
	b.CANamespace = &value
	return b
}

// WithEnrollID sets the EnrollID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnrollID field is set to the value of the last call.
func (b *CAEnrollmentSpecApplyConfiguration) WithEnrollID(value string) *CAEnrollmentSpecApplyConfiguration {
	b.EnrollID = &value
	return b
}

// WithEnrollSecretRef sets the EnrollSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnrollSecretRef field is set to the value of the last call.
func (b *CAEnrollmentSpecApplyConfiguration) WithEnrollSecretRef(value *CAEnrollmentSecretRefApplyConfiguration) *CAEnrollmentSpecApplyConfiguration {
	b.EnrollSecretRef = value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *CAEnrollmentSpecApplyConfiguration) WithType(value string) *CAEnrollmentSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithAffiliation sets the Affiliation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affiliation field is set to the value of the last call.
func (b *CAEnrollmentSpecApplyConfiguration) WithAffiliation(value string) *CAEnrollmentSpecApplyConfiguration {
	b.Affiliation = &value
	return b
}

// WithAttrs adds the given value to the Attrs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Attrs field.
func (b *CAEnrollmentSpecApplyConfiguration) WithAttrs(values ...*CAEnrollmentAttrApplyConfiguration) *CAEnrollmentSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAttrs")
		}
		b.Attrs = append(b.Attrs, *values[i])
	}
	return b
}

// WithMaxEnrollments sets the MaxEnrollments field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxEnrollments field is set to the value of the last call.
func (b *CAEnrollmentSpecApplyConfiguration) WithMaxEnrollments(value int) *CAEnrollmentSpecApplyConfiguration {
	b.MaxEnrollments = &value
	return b
}

// WithOutputSecretName sets the OutputSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OutputSecretName field is set to the value of the last call.
func (b *CAEnrollmentSpecApplyConfiguration) WithOutputSecretName(value string) *CAEnrollmentSpecApplyConfiguration {
	b.OutputSecretName = &value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *CAEnrollmentSpecApplyConfiguration) WithTLS(value *CAEnrollmentTLSApplyConfiguration) *CAEnrollmentSpecApplyConfiguration {
	b.TLS = value
	return b
}
