/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ChannelConfigApplyConfiguration represents a declarative configuration of the ChannelConfig type for use
// with apply.
type ChannelConfigApplyConfiguration struct {
	Name    *string `json:"name,omitempty"`
	Default *bool   `json:"default,omitempty"`
}

// ChannelConfigApplyConfiguration constructs a declarative configuration of the ChannelConfig type for use with
// apply.
func ChannelConfig() *ChannelConfigApplyConfiguration {
	return &ChannelConfigApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ChannelConfigApplyConfiguration) WithName(value string) *ChannelConfigApplyConfiguration {
	b.Name = &value
	return b
}

// WithDefault sets the Default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Default field is set to the value of the last call.
func (b *ChannelConfigApplyConfiguration) WithDefault(value bool) *ChannelConfigApplyConfiguration {
	b.Default = &value
	return b
}
