/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ChildCRDStatusesApplyConfiguration represents a declarative configuration of the ChildCRDStatuses type for use
// with apply.
type ChildCRDStatusesApplyConfiguration struct {
	Consenter *ChildCRDStatusApplyConfiguration  `json:"consenter,omitempty"`
	Assembler *ChildCRDStatusApplyConfiguration  `json:"assembler,omitempty"`
	Router    *ChildCRDStatusApplyConfiguration  `json:"router,omitempty"`
	Batchers  []ChildCRDStatusApplyConfiguration `json:"batchers,omitempty"`
}

// ChildCRDStatusesApplyConfiguration constructs a declarative configuration of the ChildCRDStatuses type for use with
// apply.
func ChildCRDStatuses() *ChildCRDStatusesApplyConfiguration {
	return &ChildCRDStatusesApplyConfiguration{}
}

// WithConsenter sets the Consenter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Consenter field is set to the value of the last call.
func (b *ChildCRDStatusesApplyConfiguration) WithConsenter(value *ChildCRDStatusApplyConfiguration) *ChildCRDStatusesApplyConfiguration {
	b.Consenter = value
	return b
}

// WithAssembler sets the Assembler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Assembler field is set to the value of the last call.
func (b *ChildCRDStatusesApplyConfiguration) WithAssembler(value *ChildCRDStatusApplyConfiguration) *ChildCRDStatusesApplyConfiguration {
	b.Assembler = value
	return b
}

// WithRouter sets the Router field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Router field is set to the value of the last call.
func (b *ChildCRDStatusesApplyConfiguration) WithRouter(value *ChildCRDStatusApplyConfiguration) *ChildCRDStatusesApplyConfiguration {
	b.Router = value
	return b
}

// WithBatchers adds the given value to the Batchers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Batchers field.
func (b *ChildCRDStatusesApplyConfiguration) WithBatchers(values ...*ChildCRDStatusApplyConfiguration) *ChildCRDStatusesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBatchers")
		}
		b.Batchers = append(b.Batchers, *values[i])
	}
	return b
}
