/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// CommonComponentConfigApplyConfiguration represents a declarative configuration of the CommonComponentConfig type for use
// with apply.
type CommonComponentConfigApplyConfiguration struct {
	Replicas         *int32                              `json:"replicas,omitempty"`
	Storage          *StorageConfigApplyConfiguration    `json:"storage,omitempty"`
	Resources        *v1.ResourceRequirements            `json:"resources,omitempty"`
	SecurityContext  *SecurityContextApplyConfiguration  `json:"securityContext,omitempty"`
	PodAnnotations   map[string]string                   `json:"podAnnotations,omitempty"`
	PodLabels        map[string]string                   `json:"podLabels,omitempty"`
	Volumes          []VolumeApplyConfiguration          `json:"volumes,omitempty"`
	Affinity         *AffinityApplyConfiguration         `json:"affinity,omitempty"`
	VolumeMounts     []VolumeMountApplyConfiguration     `json:"volumeMounts,omitempty"`
	ImagePullSecrets []ImagePullSecretApplyConfiguration `json:"imagePullSecrets,omitempty"`
	Tolerations      []TolerationApplyConfiguration      `json:"tolerations,omitempty"`
}

// CommonComponentConfigApplyConfiguration constructs a declarative configuration of the CommonComponentConfig type for use with
// apply.
func CommonComponentConfig() *CommonComponentConfigApplyConfiguration {
	return &CommonComponentConfigApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *CommonComponentConfigApplyConfiguration) WithReplicas(value int32) *CommonComponentConfigApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *CommonComponentConfigApplyConfiguration) WithStorage(value *StorageConfigApplyConfiguration) *CommonComponentConfigApplyConfiguration {
	b.Storage = value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *CommonComponentConfigApplyConfiguration) WithResources(value v1.ResourceRequirements) *CommonComponentConfigApplyConfiguration {
	b.Resources = &value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *CommonComponentConfigApplyConfiguration) WithSecurityContext(value *SecurityContextApplyConfiguration) *CommonComponentConfigApplyConfiguration {
	b.SecurityContext = value
	return b
}

// WithPodAnnotations puts the entries into the PodAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodAnnotations field,
// overwriting an existing map entries in PodAnnotations field with the same key.
func (b *CommonComponentConfigApplyConfiguration) WithPodAnnotations(entries map[string]string) *CommonComponentConfigApplyConfiguration {
	if b.PodAnnotations == nil && len(entries) > 0 {
		b.PodAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodAnnotations[k] = v
	}
	return b
}

// WithPodLabels puts the entries into the PodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodLabels field,
// overwriting an existing map entries in PodLabels field with the same key.
func (b *CommonComponentConfigApplyConfiguration) WithPodLabels(entries map[string]string) *CommonComponentConfigApplyConfiguration {
	if b.PodLabels == nil && len(entries) > 0 {
		b.PodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodLabels[k] = v
	}
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *CommonComponentConfigApplyConfiguration) WithVolumes(values ...*VolumeApplyConfiguration) *CommonComponentConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumes")
		}
		b.Volumes = append(b.Volumes, *values[i])
	}
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *CommonComponentConfigApplyConfiguration) WithAffinity(value *AffinityApplyConfiguration) *CommonComponentConfigApplyConfiguration {
	b.Affinity = value
	return b
}

// WithVolumeMounts adds the given value to the VolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeMounts field.
func (b *CommonComponentConfigApplyConfiguration) WithVolumeMounts(values ...*VolumeMountApplyConfiguration) *CommonComponentConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumeMounts")
		}
		b.VolumeMounts = append(b.VolumeMounts, *values[i])
	}
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *CommonComponentConfigApplyConfiguration) WithImagePullSecrets(values ...*ImagePullSecretApplyConfiguration) *CommonComponentConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithImagePullSecrets")
		}
		b.ImagePullSecrets = append(b.ImagePullSecrets, *values[i])
	}
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *CommonComponentConfigApplyConfiguration) WithTolerations(values ...*TolerationApplyConfiguration) *CommonComponentConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTolerations")
		}
		b.Tolerations = append(b.Tolerations, *values[i])
	}
	return b
}
