/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ComponentStatusApplyConfiguration represents a declarative configuration of the ComponentStatus type for use
// with apply.
type ComponentStatusApplyConfiguration struct {
	Ready          *bool    `json:"ready,omitempty"`
	ReplicasReady  *int32   `json:"replicasReady,omitempty"`
	ReplicasTotal  *int32   `json:"replicasTotal,omitempty"`
	LastUpdateTime *v1.Time `json:"lastUpdateTime,omitempty"`
}

// ComponentStatusApplyConfiguration constructs a declarative configuration of the ComponentStatus type for use with
// apply.
func ComponentStatus() *ComponentStatusApplyConfiguration {
	return &ComponentStatusApplyConfiguration{}
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithReady(value bool) *ComponentStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithReplicasReady sets the ReplicasReady field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplicasReady field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithReplicasReady(value int32) *ComponentStatusApplyConfiguration {
	b.ReplicasReady = &value
	return b
}

// WithReplicasTotal sets the ReplicasTotal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplicasTotal field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithReplicasTotal(value int32) *ComponentStatusApplyConfiguration {
	b.ReplicasTotal = &value
	return b
}

// WithLastUpdateTime sets the LastUpdateTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdateTime field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithLastUpdateTime(value v1.Time) *ComponentStatusApplyConfiguration {
	b.LastUpdateTime = &value
	return b
}
