/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ConfigTemplateReferenceApplyConfiguration represents a declarative configuration of the ConfigTemplateReference type for use
// with apply.
type ConfigTemplateReferenceApplyConfiguration struct {
	ConfigMapName *string `json:"configMapName,omitempty"`
	Key           *string `json:"key,omitempty"`
}

// ConfigTemplateReferenceApplyConfiguration constructs a declarative configuration of the ConfigTemplateReference type for use with
// apply.
func ConfigTemplateReference() *ConfigTemplateReferenceApplyConfiguration {
	return &ConfigTemplateReferenceApplyConfiguration{}
}

// WithConfigMapName sets the ConfigMapName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMapName field is set to the value of the last call.
func (b *ConfigTemplateReferenceApplyConfiguration) WithConfigMapName(value string) *ConfigTemplateReferenceApplyConfiguration {
	b.ConfigMapName = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ConfigTemplateReferenceApplyConfiguration) WithKey(value string) *ConfigTemplateReferenceApplyConfiguration {
	b.Key = &value
	return b
}
