/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ConsenterConfigApplyConfiguration represents a declarative configuration of the ConsenterConfig type for use
// with apply.
type ConsenterConfigApplyConfiguration struct {
	Host        *string                                `json:"host,omitempty"`
	Port        *int32                                 `json:"port,omitempty"`
	SignCertRef *SecretKeyNSSelectorApplyConfiguration `json:"signCertRef,omitempty"`
	TLSCertRef  *SecretKeyNSSelectorApplyConfiguration `json:"tlsCertRef,omitempty"`
}

// ConsenterConfigApplyConfiguration constructs a declarative configuration of the ConsenterConfig type for use with
// apply.
func ConsenterConfig() *ConsenterConfigApplyConfiguration {
	return &ConsenterConfigApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *ConsenterConfigApplyConfiguration) WithHost(value string) *ConsenterConfigApplyConfiguration {
	b.Host = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ConsenterConfigApplyConfiguration) WithPort(value int32) *ConsenterConfigApplyConfiguration {
	b.Port = &value
	return b
}

// WithSignCertRef sets the SignCertRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SignCertRef field is set to the value of the last call.
func (b *ConsenterConfigApplyConfiguration) WithSignCertRef(value *SecretKeyNSSelectorApplyConfiguration) *ConsenterConfigApplyConfiguration {
	b.SignCertRef = value
	return b
}

// WithTLSCertRef sets the TLSCertRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSCertRef field is set to the value of the last call.
func (b *ConsenterConfigApplyConfiguration) WithTLSCertRef(value *SecretKeyNSSelectorApplyConfiguration) *ConsenterConfigApplyConfiguration {
	b.TLSCertRef = value
	return b
}
