/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ConsensusConfigApplyConfiguration represents a declarative configuration of the ConsensusConfig type for use
// with apply.
type ConsensusConfigApplyConfiguration struct {
	SmartBFT *SmartBFTConfigApplyConfiguration `json:"smartBFT,omitempty"`
}

// ConsensusConfigApplyConfiguration constructs a declarative configuration of the ConsensusConfig type for use with
// apply.
func ConsensusConfig() *ConsensusConfigApplyConfiguration {
	return &ConsensusConfigApplyConfiguration{}
}

// WithSmartBFT sets the SmartBFT field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SmartBFT field is set to the value of the last call.
func (b *ConsensusConfigApplyConfiguration) WithSmartBFT(value *SmartBFTConfigApplyConfiguration) *ConsensusConfigApplyConfiguration {
	b.SmartBFT = value
	return b
}
