/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// EndorserStatusApplyConfiguration represents a declarative configuration of the EndorserStatus type for use
// with apply.
type EndorserStatusApplyConfiguration struct {
	Status               *apiv1alpha1.DeploymentStatus    `json:"status,omitempty"`
	Message              *string                          `json:"message,omitempty"`
	Conditions           []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	CoreConfigSecretName *string                          `json:"coreConfigSecretName,omitempty"`
	CertificateSecrets   map[string]string                `json:"certificateSecrets,omitempty"`
	ServiceEndpoint      *string                          `json:"serviceEndpoint,omitempty"`
	P2PEndpoint          *string                          `json:"p2pEndpoint,omitempty"`
}

// EndorserStatusApplyConfiguration constructs a declarative configuration of the EndorserStatus type for use with
// apply.
func EndorserStatus() *EndorserStatusApplyConfiguration {
	return &EndorserStatusApplyConfiguration{}
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *EndorserStatusApplyConfiguration) WithStatus(value apiv1alpha1.DeploymentStatus) *EndorserStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *EndorserStatusApplyConfiguration) WithMessage(value string) *EndorserStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *EndorserStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *EndorserStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithCoreConfigSecretName sets the CoreConfigSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CoreConfigSecretName field is set to the value of the last call.
func (b *EndorserStatusApplyConfiguration) WithCoreConfigSecretName(value string) *EndorserStatusApplyConfiguration {
	b.CoreConfigSecretName = &value
	return b
}

// WithCertificateSecrets puts the entries into the CertificateSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the CertificateSecrets field,
// overwriting an existing map entries in CertificateSecrets field with the same key.
func (b *EndorserStatusApplyConfiguration) WithCertificateSecrets(entries map[string]string) *EndorserStatusApplyConfiguration {
	if b.CertificateSecrets == nil && len(entries) > 0 {
		b.CertificateSecrets = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.CertificateSecrets[k] = v
	}
	return b
}

// WithServiceEndpoint sets the ServiceEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceEndpoint field is set to the value of the last call.
func (b *EndorserStatusApplyConfiguration) WithServiceEndpoint(value string) *EndorserStatusApplyConfiguration {
	b.ServiceEndpoint = &value
	return b
}

// WithP2PEndpoint sets the P2PEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the P2PEndpoint field is set to the value of the last call.
func (b *EndorserStatusApplyConfiguration) WithP2PEndpoint(value string) *EndorserStatusApplyConfiguration {
	b.P2PEndpoint = &value
	return b
}
