/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EndorserCoreConfigApplyConfiguration represents a declarative configuration of the EndorserCoreConfig type for use
// with apply.
type EndorserCoreConfigApplyConfiguration struct {
	Logging *LoggingConfigApplyConfiguration `json:"logging,omitempty"`
	FSC     *FSCConfigApplyConfiguration     `json:"fsc,omitempty"`
	Fabric  *FabricConfigApplyConfiguration  `json:"fabric,omitempty"`
	Token   *TokenConfigApplyConfiguration   `json:"token,omitempty"`
}

// EndorserCoreConfigApplyConfiguration constructs a declarative configuration of the EndorserCoreConfig type for use with
// apply.
func EndorserCoreConfig() *EndorserCoreConfigApplyConfiguration {
	return &EndorserCoreConfigApplyConfiguration{}
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *EndorserCoreConfigApplyConfiguration) WithLogging(value *LoggingConfigApplyConfiguration) *EndorserCoreConfigApplyConfiguration {
	b.Logging = value
	return b
}

// WithFSC sets the FSC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FSC field is set to the value of the last call.
func (b *EndorserCoreConfigApplyConfiguration) WithFSC(value *FSCConfigApplyConfiguration) *EndorserCoreConfigApplyConfiguration {
	b.FSC = value
	return b
}

// WithFabric sets the Fabric field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fabric field is set to the value of the last call.
func (b *EndorserCoreConfigApplyConfiguration) WithFabric(value *FabricConfigApplyConfiguration) *EndorserCoreConfigApplyConfiguration {
	b.Fabric = value
	return b
}

// WithToken sets the Token field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Token field is set to the value of the last call.
func (b *EndorserCoreConfigApplyConfiguration) WithToken(value *TokenConfigApplyConfiguration) *EndorserCoreConfigApplyConfiguration {
	b.Token = value
	return b
}
