/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EndpointConfigApplyConfiguration represents a declarative configuration of the EndpointConfig type for use
// with apply.
type EndpointConfigApplyConfiguration struct {
	Resolvers []EndpointResolverApplyConfiguration `json:"resolvers,omitempty"`
}

// EndpointConfigApplyConfiguration constructs a declarative configuration of the EndpointConfig type for use with
// apply.
func EndpointConfig() *EndpointConfigApplyConfiguration {
	return &EndpointConfigApplyConfiguration{}
}

// WithResolvers adds the given value to the Resolvers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Resolvers field.
func (b *EndpointConfigApplyConfiguration) WithResolvers(values ...*EndpointResolverApplyConfiguration) *EndpointConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResolvers")
		}
		b.Resolvers = append(b.Resolvers, *values[i])
	}
	return b
}
