/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FabricNetworkConfigApplyConfiguration represents a declarative configuration of the FabricNetworkConfig type for use
// with apply.
type FabricNetworkConfigApplyConfiguration struct {
	FSCEndorsement *FSCEndorsementConfigApplyConfiguration `json:"fsc_endorsement,omitempty"`
}

// FabricNetworkConfigApplyConfiguration constructs a declarative configuration of the FabricNetworkConfig type for use with
// apply.
func FabricNetworkConfig() *FabricNetworkConfigApplyConfiguration {
	return &FabricNetworkConfigApplyConfiguration{}
}

// WithFSCEndorsement sets the FSCEndorsement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FSCEndorsement field is set to the value of the last call.
func (b *FabricNetworkConfigApplyConfiguration) WithFSCEndorsement(value *FSCEndorsementConfigApplyConfiguration) *FabricNetworkConfigApplyConfiguration {
	b.FSCEndorsement = value
	return b
}
