/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FabricCAItemBCCSPApplyConfiguration represents a declarative configuration of the FabricCAItemBCCSP type for use
// with apply.
type FabricCAItemBCCSPApplyConfiguration struct {
	Default *string                                `json:"default,omitempty"`
	SW      *FabricCAItemBCCSPSWApplyConfiguration `json:"sw,omitempty"`
}

// FabricCAItemBCCSPApplyConfiguration constructs a declarative configuration of the FabricCAItemBCCSP type for use with
// apply.
func FabricCAItemBCCSP() *FabricCAItemBCCSPApplyConfiguration {
	return &FabricCAItemBCCSPApplyConfiguration{}
}

// WithDefault sets the Default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Default field is set to the value of the last call.
func (b *FabricCAItemBCCSPApplyConfiguration) WithDefault(value string) *FabricCAItemBCCSPApplyConfiguration {
	b.Default = &value
	return b
}

// WithSW sets the SW field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SW field is set to the value of the last call.
func (b *FabricCAItemBCCSPApplyConfiguration) WithSW(value *FabricCAItemBCCSPSWApplyConfiguration) *FabricCAItemBCCSPApplyConfiguration {
	b.SW = value
	return b
}
