/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
)

// FabricCAVaultApplyConfiguration represents a declarative configuration of the FabricCAVault type for use
// with apply.
type FabricCAVaultApplyConfiguration struct {
	Vault *apiv1alpha1.FabricCAVaultConfig `json:"vault,omitempty"`
}

// FabricCAVaultApplyConfiguration constructs a declarative configuration of the FabricCAVault type for use with
// apply.
func FabricCAVault() *FabricCAVaultApplyConfiguration {
	return &FabricCAVaultApplyConfiguration{}
}

// WithVault sets the Vault field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vault field is set to the value of the last call.
func (b *FabricCAVaultApplyConfiguration) WithVault(value apiv1alpha1.FabricCAVaultConfig) *FabricCAVaultApplyConfiguration {
	b.Vault = &value
	return b
}
