/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FabricCATLSConfigApplyConfiguration represents a declarative configuration of the FabricCATLSConfig type for use
// with apply.
type FabricCATLSConfigApplyConfiguration struct {
	SecretName *string `json:"secretName,omitempty"`
	Enabled    *bool   `json:"enabled,omitempty"`
}

// FabricCATLSConfigApplyConfiguration constructs a declarative configuration of the FabricCATLSConfig type for use with
// apply.
func FabricCATLSConfig() *FabricCATLSConfigApplyConfiguration {
	return &FabricCATLSConfigApplyConfiguration{}
}

// WithSecretName sets the SecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretName field is set to the value of the last call.
func (b *FabricCATLSConfigApplyConfiguration) WithSecretName(value string) *FabricCATLSConfigApplyConfiguration {
	b.SecretName = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *FabricCATLSConfigApplyConfiguration) WithEnabled(value bool) *FabricCATLSConfigApplyConfiguration {
	b.Enabled = &value
	return b
}
