/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FSCIdentityApplyConfiguration represents a declarative configuration of the FSCIdentity type for use
// with apply.
type FSCIdentityApplyConfiguration struct {
	Cert *CertFileConfigApplyConfiguration `json:"cert,omitempty"`
	Key  *KeyFileConfigApplyConfiguration  `json:"key,omitempty"`
}

// FSCIdentityApplyConfiguration constructs a declarative configuration of the FSCIdentity type for use with
// apply.
func FSCIdentity() *FSCIdentityApplyConfiguration {
	return &FSCIdentityApplyConfiguration{}
}

// WithCert sets the Cert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cert field is set to the value of the last call.
func (b *FSCIdentityApplyConfiguration) WithCert(value *CertFileConfigApplyConfiguration) *FSCIdentityApplyConfiguration {
	b.Cert = value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *FSCIdentityApplyConfiguration) WithKey(value *KeyFileConfigApplyConfiguration) *FSCIdentityApplyConfiguration {
	b.Key = value
	return b
}
