/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GenesisSpecApplyConfiguration represents a declarative configuration of the GenesisSpec type for use
// with apply.
type GenesisSpecApplyConfiguration struct {
	ChannelID            *string                                     `json:"channelID,omitempty"`
	ConfigTemplate       *ConfigTemplateReferenceApplyConfiguration  `json:"configTemplate,omitempty"`
	OrdererOrganizations []OrdererOrganizationApplyConfiguration     `json:"ordererOrganizations,omitempty"`
	ApplicationOrgs      []ApplicationOrganizationApplyConfiguration `json:"applicationOrgs,omitempty"`
	OrdererNodes         []OrdererNodeApplyConfiguration             `json:"ordererNodes,omitempty"`
	Output               *GenesisOutputApplyConfiguration            `json:"output,omitempty"`
}

// GenesisSpecApplyConfiguration constructs a declarative configuration of the GenesisSpec type for use with
// apply.
func GenesisSpec() *GenesisSpecApplyConfiguration {
	return &GenesisSpecApplyConfiguration{}
}

// WithChannelID sets the ChannelID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChannelID field is set to the value of the last call.
func (b *GenesisSpecApplyConfiguration) WithChannelID(value string) *GenesisSpecApplyConfiguration {
	b.ChannelID = &value
	return b
}

// WithConfigTemplate sets the ConfigTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigTemplate field is set to the value of the last call.
func (b *GenesisSpecApplyConfiguration) WithConfigTemplate(value *ConfigTemplateReferenceApplyConfiguration) *GenesisSpecApplyConfiguration {
	b.ConfigTemplate = value
	return b
}

// WithOrdererOrganizations adds the given value to the OrdererOrganizations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OrdererOrganizations field.
func (b *GenesisSpecApplyConfiguration) WithOrdererOrganizations(values ...*OrdererOrganizationApplyConfiguration) *GenesisSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOrdererOrganizations")
		}
		b.OrdererOrganizations = append(b.OrdererOrganizations, *values[i])
	}
	return b
}

// WithApplicationOrgs adds the given value to the ApplicationOrgs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ApplicationOrgs field.
func (b *GenesisSpecApplyConfiguration) WithApplicationOrgs(values ...*ApplicationOrganizationApplyConfiguration) *GenesisSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithApplicationOrgs")
		}
		b.ApplicationOrgs = append(b.ApplicationOrgs, *values[i])
	}
	return b
}

// WithOrdererNodes adds the given value to the OrdererNodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OrdererNodes field.
func (b *GenesisSpecApplyConfiguration) WithOrdererNodes(values ...*OrdererNodeApplyConfiguration) *GenesisSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOrdererNodes")
		}
		b.OrdererNodes = append(b.OrdererNodes, *values[i])
	}
	return b
}

// WithOutput sets the Output field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Output field is set to the value of the last call.
func (b *GenesisSpecApplyConfiguration) WithOutput(value *GenesisOutputApplyConfiguration) *GenesisSpecApplyConfiguration {
	b.Output = value
	return b
}
