/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GenesisOutputApplyConfiguration represents a declarative configuration of the GenesisOutput type for use
// with apply.
type GenesisOutputApplyConfiguration struct {
	SecretName *string `json:"secretName,omitempty"`
	BlockKey   *string `json:"blockKey,omitempty"`
}

// GenesisOutputApplyConfiguration constructs a declarative configuration of the GenesisOutput type for use with
// apply.
func GenesisOutput() *GenesisOutputApplyConfiguration {
	return &GenesisOutputApplyConfiguration{}
}

// WithSecretName sets the SecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretName field is set to the value of the last call.
func (b *GenesisOutputApplyConfiguration) WithSecretName(value string) *GenesisOutputApplyConfiguration {
	b.SecretName = &value
	return b
}

// WithBlockKey sets the BlockKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BlockKey field is set to the value of the last call.
func (b *GenesisOutputApplyConfiguration) WithBlockKey(value string) *GenesisOutputApplyConfiguration {
	b.BlockKey = &value
	return b
}
