/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// IdentityEnrollmentApplyConfiguration represents a declarative configuration of the IdentityEnrollment type for use
// with apply.
type IdentityEnrollmentApplyConfiguration struct {
	CARef           *IdentityCARefApplyConfiguration            `json:"caRef,omitempty"`
	EnrollID        *string                                     `json:"enrollID,omitempty"`
	EnrollSecretRef *SecretKeyNSSelectorApplyConfiguration      `json:"enrollSecretRef,omitempty"`
	Affiliation     *string                                     `json:"affiliation,omitempty"`
	Attrs           []IdentityAttributeApplyConfiguration       `json:"attrs,omitempty"`
	EnrollTLS       *bool                                       `json:"enrollTLS,omitempty"`
	TLSCARef        *IdentityCARefApplyConfiguration            `json:"tlsCARef,omitempty"`
	Idemix          *IdentityIdemixEnrollmentApplyConfiguration `json:"idemix,omitempty"`
}

// IdentityEnrollmentApplyConfiguration constructs a declarative configuration of the IdentityEnrollment type for use with
// apply.
func IdentityEnrollment() *IdentityEnrollmentApplyConfiguration {
	return &IdentityEnrollmentApplyConfiguration{}
}

// WithCARef sets the CARef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CARef field is set to the value of the last call.
func (b *IdentityEnrollmentApplyConfiguration) WithCARef(value *IdentityCARefApplyConfiguration) *IdentityEnrollmentApplyConfiguration {
	b.CARef = value
	return b
}

// WithEnrollID sets the EnrollID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnrollID field is set to the value of the last call.
func (b *IdentityEnrollmentApplyConfiguration) WithEnrollID(value string) *IdentityEnrollmentApplyConfiguration {
	b.EnrollID = &value
	return b
}

// WithEnrollSecretRef sets the EnrollSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnrollSecretRef field is set to the value of the last call.
func (b *IdentityEnrollmentApplyConfiguration) WithEnrollSecretRef(value *SecretKeyNSSelectorApplyConfiguration) *IdentityEnrollmentApplyConfiguration {
	b.EnrollSecretRef = value
	return b
}

// WithAffiliation sets the Affiliation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affiliation field is set to the value of the last call.
func (b *IdentityEnrollmentApplyConfiguration) WithAffiliation(value string) *IdentityEnrollmentApplyConfiguration {
	b.Affiliation = &value
	return b
}

// WithAttrs adds the given value to the Attrs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Attrs field.
func (b *IdentityEnrollmentApplyConfiguration) WithAttrs(values ...*IdentityAttributeApplyConfiguration) *IdentityEnrollmentApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAttrs")
		}
		b.Attrs = append(b.Attrs, *values[i])
	}
	return b
}

// WithEnrollTLS sets the EnrollTLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnrollTLS field is set to the value of the last call.
func (b *IdentityEnrollmentApplyConfiguration) WithEnrollTLS(value bool) *IdentityEnrollmentApplyConfiguration {
	b.EnrollTLS = &value
	return b
}

// WithTLSCARef sets the TLSCARef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSCARef field is set to the value of the last call.
func (b *IdentityEnrollmentApplyConfiguration) WithTLSCARef(value *IdentityCARefApplyConfiguration) *IdentityEnrollmentApplyConfiguration {
	b.TLSCARef = value
	return b
}

// WithIdemix sets the Idemix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Idemix field is set to the value of the last call.
func (b *IdentityEnrollmentApplyConfiguration) WithIdemix(value *IdentityIdemixEnrollmentApplyConfiguration) *IdentityEnrollmentApplyConfiguration {
	b.Idemix = value
	return b
}
