/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// IdentitySpecApplyConfiguration represents a declarative configuration of the IdentitySpec type for use
// with apply.
type IdentitySpecApplyConfiguration struct {
	Type       *string                               `json:"type,omitempty"`
	MspID      *string                               `json:"mspID,omitempty"`
	Enrollment *IdentityEnrollmentApplyConfiguration `json:"enrollment,omitempty"`
	Output     *IdentityOutputApplyConfiguration     `json:"output,omitempty"`
}

// IdentitySpecApplyConfiguration constructs a declarative configuration of the IdentitySpec type for use with
// apply.
func IdentitySpec() *IdentitySpecApplyConfiguration {
	return &IdentitySpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *IdentitySpecApplyConfiguration) WithType(value string) *IdentitySpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithMspID sets the MspID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MspID field is set to the value of the last call.
func (b *IdentitySpecApplyConfiguration) WithMspID(value string) *IdentitySpecApplyConfiguration {
	b.MspID = &value
	return b
}

// WithEnrollment sets the Enrollment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enrollment field is set to the value of the last call.
func (b *IdentitySpecApplyConfiguration) WithEnrollment(value *IdentityEnrollmentApplyConfiguration) *IdentitySpecApplyConfiguration {
	b.Enrollment = value
	return b
}

// WithOutput sets the Output field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Output field is set to the value of the last call.
func (b *IdentitySpecApplyConfiguration) WithOutput(value *IdentityOutputApplyConfiguration) *IdentitySpecApplyConfiguration {
	b.Output = value
	return b
}
