/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// IdentityOutputSecretsApplyConfiguration represents a declarative configuration of the IdentityOutputSecrets type for use
// with apply.
type IdentityOutputSecretsApplyConfiguration struct {
	SignCert   *string `json:"signCert,omitempty"`
	SignKey    *string `json:"signKey,omitempty"`
	SignCACert *string `json:"signCACert,omitempty"`
	TLSCert    *string `json:"tlsCert,omitempty"`
	TLSKey     *string `json:"tlsKey,omitempty"`
	TLSCACert  *string `json:"tlsCACert,omitempty"`
	IdemixCred *string `json:"idemixCred,omitempty"`
}

// IdentityOutputSecretsApplyConfiguration constructs a declarative configuration of the IdentityOutputSecrets type for use with
// apply.
func IdentityOutputSecrets() *IdentityOutputSecretsApplyConfiguration {
	return &IdentityOutputSecretsApplyConfiguration{}
}

// WithSignCert sets the SignCert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SignCert field is set to the value of the last call.
func (b *IdentityOutputSecretsApplyConfiguration) WithSignCert(value string) *IdentityOutputSecretsApplyConfiguration {
	b.SignCert = &value
	return b
}

// WithSignKey sets the SignKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SignKey field is set to the value of the last call.
func (b *IdentityOutputSecretsApplyConfiguration) WithSignKey(value string) *IdentityOutputSecretsApplyConfiguration {
	b.SignKey = &value
	return b
}

// WithSignCACert sets the SignCACert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SignCACert field is set to the value of the last call.
func (b *IdentityOutputSecretsApplyConfiguration) WithSignCACert(value string) *IdentityOutputSecretsApplyConfiguration {
	b.SignCACert = &value
	return b
}

// WithTLSCert sets the TLSCert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSCert field is set to the value of the last call.
func (b *IdentityOutputSecretsApplyConfiguration) WithTLSCert(value string) *IdentityOutputSecretsApplyConfiguration {
	b.TLSCert = &value
	return b
}

// WithTLSKey sets the TLSKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSKey field is set to the value of the last call.
func (b *IdentityOutputSecretsApplyConfiguration) WithTLSKey(value string) *IdentityOutputSecretsApplyConfiguration {
	b.TLSKey = &value
	return b
}

// WithTLSCACert sets the TLSCACert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSCACert field is set to the value of the last call.
func (b *IdentityOutputSecretsApplyConfiguration) WithTLSCACert(value string) *IdentityOutputSecretsApplyConfiguration {
	b.TLSCACert = &value
	return b
}

// WithIdemixCred sets the IdemixCred field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdemixCred field is set to the value of the last call.
func (b *IdentityOutputSecretsApplyConfiguration) WithIdemixCred(value string) *IdentityOutputSecretsApplyConfiguration {
	b.IdemixCred = &value
	return b
}
