/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// IdentityCARefApplyConfiguration represents a declarative configuration of the IdentityCARef type for use
// with apply.
type IdentityCARefApplyConfiguration struct {
	Name      *string                                `json:"name,omitempty"`
	Namespace *string                                `json:"namespace,omitempty"`
	CACertRef *SecretKeyNSSelectorApplyConfiguration `json:"caCertRef,omitempty"`
}

// IdentityCARefApplyConfiguration constructs a declarative configuration of the IdentityCARef type for use with
// apply.
func IdentityCARef() *IdentityCARefApplyConfiguration {
	return &IdentityCARefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *IdentityCARefApplyConfiguration) WithName(value string) *IdentityCARefApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *IdentityCARefApplyConfiguration) WithNamespace(value string) *IdentityCARefApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithCACertRef sets the CACertRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CACertRef field is set to the value of the last call.
func (b *IdentityCARefApplyConfiguration) WithCACertRef(value *SecretKeyNSSelectorApplyConfiguration) *IdentityCARefApplyConfiguration {
	b.CACertRef = value
	return b
}
