/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ImagePullSecretApplyConfiguration represents a declarative configuration of the ImagePullSecret type for use
// with apply.
type ImagePullSecretApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// ImagePullSecretApplyConfiguration constructs a declarative configuration of the ImagePullSecret type for use with
// apply.
func ImagePullSecret() *ImagePullSecretApplyConfiguration {
	return &ImagePullSecretApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ImagePullSecretApplyConfiguration) WithName(value string) *ImagePullSecretApplyConfiguration {
	b.Name = &value
	return b
}
