/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ManualProviderConfigApplyConfiguration represents a declarative configuration of the ManualProviderConfig type for use
// with apply.
type ManualProviderConfigApplyConfiguration struct {
	SecretRef *SecretRefApplyConfiguration `json:"secretRef,omitempty"`
	CertKey   *string                      `json:"certKey,omitempty"`
	KeyKey    *string                      `json:"keyKey,omitempty"`
	CAKey     *string                      `json:"caKey,omitempty"`
}

// ManualProviderConfigApplyConfiguration constructs a declarative configuration of the ManualProviderConfig type for use with
// apply.
func ManualProviderConfig() *ManualProviderConfigApplyConfiguration {
	return &ManualProviderConfigApplyConfiguration{}
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *ManualProviderConfigApplyConfiguration) WithSecretRef(value *SecretRefApplyConfiguration) *ManualProviderConfigApplyConfiguration {
	b.SecretRef = value
	return b
}

// WithCertKey sets the CertKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertKey field is set to the value of the last call.
func (b *ManualProviderConfigApplyConfiguration) WithCertKey(value string) *ManualProviderConfigApplyConfiguration {
	b.CertKey = &value
	return b
}

// WithKeyKey sets the KeyKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyKey field is set to the value of the last call.
func (b *ManualProviderConfigApplyConfiguration) WithKeyKey(value string) *ManualProviderConfigApplyConfiguration {
	b.KeyKey = &value
	return b
}

// WithCAKey sets the CAKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CAKey field is set to the value of the last call.
func (b *ManualProviderConfigApplyConfiguration) WithCAKey(value string) *ManualProviderConfigApplyConfiguration {
	b.CAKey = &value
	return b
}
