/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NamespaceSpecApplyConfiguration represents a declarative configuration of the NamespaceSpec type for use
// with apply.
type NamespaceSpecApplyConfiguration struct {
	Name                *string                         `json:"name,omitempty"`
	Orderer             *string                         `json:"orderer,omitempty"`
	CACert              *SecretKeyRefApplyConfiguration `json:"caCert,omitempty"`
	MSPID               *string                         `json:"mspID,omitempty"`
	Identity            *SecretKeyRefApplyConfiguration `json:"identity,omitempty"`
	Channel             *string                         `json:"channel,omitempty"`
	VerificationKeyPath *string                         `json:"verificationKeyPath,omitempty"`
	Version             *int                            `json:"version,omitempty"`
}

// NamespaceSpecApplyConfiguration constructs a declarative configuration of the NamespaceSpec type for use with
// apply.
func NamespaceSpec() *NamespaceSpecApplyConfiguration {
	return &NamespaceSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NamespaceSpecApplyConfiguration) WithName(value string) *NamespaceSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithOrderer sets the Orderer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Orderer field is set to the value of the last call.
func (b *NamespaceSpecApplyConfiguration) WithOrderer(value string) *NamespaceSpecApplyConfiguration {
	b.Orderer = &value
	return b
}

// WithCACert sets the CACert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CACert field is set to the value of the last call.
func (b *NamespaceSpecApplyConfiguration) WithCACert(value *SecretKeyRefApplyConfiguration) *NamespaceSpecApplyConfiguration {
	b.CACert = value
	return b
}

// WithMSPID sets the MSPID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MSPID field is set to the value of the last call.
func (b *NamespaceSpecApplyConfiguration) WithMSPID(value string) *NamespaceSpecApplyConfiguration {
	b.MSPID = &value
	return b
}

// WithIdentity sets the Identity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Identity field is set to the value of the last call.
func (b *NamespaceSpecApplyConfiguration) WithIdentity(value *SecretKeyRefApplyConfiguration) *NamespaceSpecApplyConfiguration {
	b.Identity = value
	return b
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *NamespaceSpecApplyConfiguration) WithChannel(value string) *NamespaceSpecApplyConfiguration {
	b.Channel = &value
	return b
}

// WithVerificationKeyPath sets the VerificationKeyPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VerificationKeyPath field is set to the value of the last call.
func (b *NamespaceSpecApplyConfiguration) WithVerificationKeyPath(value string) *NamespaceSpecApplyConfiguration {
	b.VerificationKeyPath = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *NamespaceSpecApplyConfiguration) WithVersion(value int) *NamespaceSpecApplyConfiguration {
	b.Version = &value
	return b
}
