/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// OrdererRouterStatusApplyConfiguration represents a declarative configuration of the OrdererRouterStatus type for use
// with apply.
type OrdererRouterStatusApplyConfiguration struct {
	Status     *apiv1alpha1.DeploymentStatus    `json:"status,omitempty"`
	Message    *string                          `json:"message,omitempty"`
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	Phase      *string                          `json:"phase,omitempty"`
}

// OrdererRouterStatusApplyConfiguration constructs a declarative configuration of the OrdererRouterStatus type for use with
// apply.
func OrdererRouterStatus() *OrdererRouterStatusApplyConfiguration {
	return &OrdererRouterStatusApplyConfiguration{}
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *OrdererRouterStatusApplyConfiguration) WithStatus(value apiv1alpha1.DeploymentStatus) *OrdererRouterStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *OrdererRouterStatusApplyConfiguration) WithMessage(value string) *OrdererRouterStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *OrdererRouterStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *OrdererRouterStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *OrdererRouterStatusApplyConfiguration) WithPhase(value string) *OrdererRouterStatusApplyConfiguration {
	b.Phase = &value
	return b
}
