/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// OrdererAssemblerSpecApplyConfiguration represents a declarative configuration of the OrdererAssemblerSpec type for use
// with apply.
type OrdererAssemblerSpecApplyConfiguration struct {
	BootstrapMode    *string                             `json:"bootstrapMode,omitempty"`
	MSPID            *string                             `json:"mspid,omitempty"`
	PartyID          *int32                              `json:"partyID,omitempty"`
	Image            *string                             `json:"image,omitempty"`
	ImageTag         *string                             `json:"imageTag,omitempty"`
	Genesis          *GenesisConfigApplyConfiguration    `json:"genesis,omitempty"`
	Replicas         *int32                              `json:"replicas,omitempty"`
	Storage          *StorageConfigApplyConfiguration    `json:"storage,omitempty"`
	Resources        *v1.ResourceRequirements            `json:"resources,omitempty"`
	SecurityContext  *SecurityContextApplyConfiguration  `json:"securityContext,omitempty"`
	PodAnnotations   map[string]string                   `json:"podAnnotations,omitempty"`
	PodLabels        map[string]string                   `json:"podLabels,omitempty"`
	Volumes          []VolumeApplyConfiguration          `json:"volumes,omitempty"`
	Affinity         *AffinityApplyConfiguration         `json:"affinity,omitempty"`
	VolumeMounts     []VolumeMountApplyConfiguration     `json:"volumeMounts,omitempty"`
	ImagePullSecrets []ImagePullSecretApplyConfiguration `json:"imagePullSecrets,omitempty"`
	Tolerations      []TolerationApplyConfiguration      `json:"tolerations,omitempty"`
	Ingress          *IngressConfigApplyConfiguration    `json:"ingress,omitempty"`
	Enrollment       *EnrollmentConfigApplyConfiguration `json:"enrollment,omitempty"`
	SANS             *SANSConfigApplyConfiguration       `json:"sans,omitempty"`
	Endpoints        []string                            `json:"endpoints,omitempty"`
	Env              []v1.EnvVar                         `json:"env,omitempty"`
	Command          []string                            `json:"command,omitempty"`
	Args             []string                            `json:"args,omitempty"`
}

// OrdererAssemblerSpecApplyConfiguration constructs a declarative configuration of the OrdererAssemblerSpec type for use with
// apply.
func OrdererAssemblerSpec() *OrdererAssemblerSpecApplyConfiguration {
	return &OrdererAssemblerSpecApplyConfiguration{}
}

// WithBootstrapMode sets the BootstrapMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootstrapMode field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithBootstrapMode(value string) *OrdererAssemblerSpecApplyConfiguration {
	b.BootstrapMode = &value
	return b
}

// WithMSPID sets the MSPID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MSPID field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithMSPID(value string) *OrdererAssemblerSpecApplyConfiguration {
	b.MSPID = &value
	return b
}

// WithPartyID sets the PartyID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PartyID field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithPartyID(value int32) *OrdererAssemblerSpecApplyConfiguration {
	b.PartyID = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithImage(value string) *OrdererAssemblerSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithImageTag sets the ImageTag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageTag field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithImageTag(value string) *OrdererAssemblerSpecApplyConfiguration {
	b.ImageTag = &value
	return b
}

// WithGenesis sets the Genesis field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Genesis field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithGenesis(value *GenesisConfigApplyConfiguration) *OrdererAssemblerSpecApplyConfiguration {
	b.Genesis = value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithReplicas(value int32) *OrdererAssemblerSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithStorage(value *StorageConfigApplyConfiguration) *OrdererAssemblerSpecApplyConfiguration {
	b.Storage = value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *OrdererAssemblerSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithSecurityContext(value *SecurityContextApplyConfiguration) *OrdererAssemblerSpecApplyConfiguration {
	b.SecurityContext = value
	return b
}

// WithPodAnnotations puts the entries into the PodAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodAnnotations field,
// overwriting an existing map entries in PodAnnotations field with the same key.
func (b *OrdererAssemblerSpecApplyConfiguration) WithPodAnnotations(entries map[string]string) *OrdererAssemblerSpecApplyConfiguration {
	if b.PodAnnotations == nil && len(entries) > 0 {
		b.PodAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodAnnotations[k] = v
	}
	return b
}

// WithPodLabels puts the entries into the PodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodLabels field,
// overwriting an existing map entries in PodLabels field with the same key.
func (b *OrdererAssemblerSpecApplyConfiguration) WithPodLabels(entries map[string]string) *OrdererAssemblerSpecApplyConfiguration {
	if b.PodLabels == nil && len(entries) > 0 {
		b.PodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodLabels[k] = v
	}
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *OrdererAssemblerSpecApplyConfiguration) WithVolumes(values ...*VolumeApplyConfiguration) *OrdererAssemblerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumes")
		}
		b.Volumes = append(b.Volumes, *values[i])
	}
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithAffinity(value *AffinityApplyConfiguration) *OrdererAssemblerSpecApplyConfiguration {
	b.Affinity = value
	return b
}

// WithVolumeMounts adds the given value to the VolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeMounts field.
func (b *OrdererAssemblerSpecApplyConfiguration) WithVolumeMounts(values ...*VolumeMountApplyConfiguration) *OrdererAssemblerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumeMounts")
		}
		b.VolumeMounts = append(b.VolumeMounts, *values[i])
	}
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *OrdererAssemblerSpecApplyConfiguration) WithImagePullSecrets(values ...*ImagePullSecretApplyConfiguration) *OrdererAssemblerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithImagePullSecrets")
		}
		b.ImagePullSecrets = append(b.ImagePullSecrets, *values[i])
	}
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *OrdererAssemblerSpecApplyConfiguration) WithTolerations(values ...*TolerationApplyConfiguration) *OrdererAssemblerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTolerations")
		}
		b.Tolerations = append(b.Tolerations, *values[i])
	}
	return b
}

// WithIngress sets the Ingress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ingress field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithIngress(value *IngressConfigApplyConfiguration) *OrdererAssemblerSpecApplyConfiguration {
	b.Ingress = value
	return b
}

// WithEnrollment sets the Enrollment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enrollment field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithEnrollment(value *EnrollmentConfigApplyConfiguration) *OrdererAssemblerSpecApplyConfiguration {
	b.Enrollment = value
	return b
}

// WithSANS sets the SANS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SANS field is set to the value of the last call.
func (b *OrdererAssemblerSpecApplyConfiguration) WithSANS(value *SANSConfigApplyConfiguration) *OrdererAssemblerSpecApplyConfiguration {
	b.SANS = value
	return b
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *OrdererAssemblerSpecApplyConfiguration) WithEndpoints(values ...string) *OrdererAssemblerSpecApplyConfiguration {
	for i := range values {
		b.Endpoints = append(b.Endpoints, values[i])
	}
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *OrdererAssemblerSpecApplyConfiguration) WithEnv(values ...v1.EnvVar) *OrdererAssemblerSpecApplyConfiguration {
	for i := range values {
		b.Env = append(b.Env, values[i])
	}
	return b
}

// WithCommand adds the given value to the Command field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Command field.
func (b *OrdererAssemblerSpecApplyConfiguration) WithCommand(values ...string) *OrdererAssemblerSpecApplyConfiguration {
	for i := range values {
		b.Command = append(b.Command, values[i])
	}
	return b
}

// WithArgs adds the given value to the Args field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Args field.
func (b *OrdererAssemblerSpecApplyConfiguration) WithArgs(values ...string) *OrdererAssemblerSpecApplyConfiguration {
	for i := range values {
		b.Args = append(b.Args, values[i])
	}
	return b
}
