/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OrdererGroupSpecApplyConfiguration represents a declarative configuration of the OrdererGroupSpec type for use
// with apply.
type OrdererGroupSpecApplyConfiguration struct {
	BootstrapMode   *string                                  `json:"bootstrapMode,omitempty"`
	MSPID           *string                                  `json:"mspid,omitempty"`
	PartyID         *int32                                   `json:"partyID,omitempty"`
	Image           *string                                  `json:"image,omitempty"`
	ImageTag        *string                                  `json:"imageTag,omitempty"`
	Common          *CommonComponentConfigApplyConfiguration `json:"common,omitempty"`
	Genesis         *GenesisConfigApplyConfiguration         `json:"genesis,omitempty"`
	Components      *OrdererComponentsApplyConfiguration     `json:"components,omitempty"`
	Enrollment      *EnrollmentConfigApplyConfiguration      `json:"enrollment,omitempty"`
	ManageChildCRDs *bool                                    `json:"manageChildCRDs,omitempty"`
}

// OrdererGroupSpecApplyConfiguration constructs a declarative configuration of the OrdererGroupSpec type for use with
// apply.
func OrdererGroupSpec() *OrdererGroupSpecApplyConfiguration {
	return &OrdererGroupSpecApplyConfiguration{}
}

// WithBootstrapMode sets the BootstrapMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootstrapMode field is set to the value of the last call.
func (b *OrdererGroupSpecApplyConfiguration) WithBootstrapMode(value string) *OrdererGroupSpecApplyConfiguration {
	b.BootstrapMode = &value
	return b
}

// WithMSPID sets the MSPID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MSPID field is set to the value of the last call.
func (b *OrdererGroupSpecApplyConfiguration) WithMSPID(value string) *OrdererGroupSpecApplyConfiguration {
	b.MSPID = &value
	return b
}

// WithPartyID sets the PartyID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PartyID field is set to the value of the last call.
func (b *OrdererGroupSpecApplyConfiguration) WithPartyID(value int32) *OrdererGroupSpecApplyConfiguration {
	b.PartyID = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *OrdererGroupSpecApplyConfiguration) WithImage(value string) *OrdererGroupSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithImageTag sets the ImageTag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageTag field is set to the value of the last call.
func (b *OrdererGroupSpecApplyConfiguration) WithImageTag(value string) *OrdererGroupSpecApplyConfiguration {
	b.ImageTag = &value
	return b
}

// WithCommon sets the Common field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Common field is set to the value of the last call.
func (b *OrdererGroupSpecApplyConfiguration) WithCommon(value *CommonComponentConfigApplyConfiguration) *OrdererGroupSpecApplyConfiguration {
	b.Common = value
	return b
}

// WithGenesis sets the Genesis field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Genesis field is set to the value of the last call.
func (b *OrdererGroupSpecApplyConfiguration) WithGenesis(value *GenesisConfigApplyConfiguration) *OrdererGroupSpecApplyConfiguration {
	b.Genesis = value
	return b
}

// WithComponents sets the Components field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Components field is set to the value of the last call.
func (b *OrdererGroupSpecApplyConfiguration) WithComponents(value *OrdererComponentsApplyConfiguration) *OrdererGroupSpecApplyConfiguration {
	b.Components = value
	return b
}

// WithEnrollment sets the Enrollment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enrollment field is set to the value of the last call.
func (b *OrdererGroupSpecApplyConfiguration) WithEnrollment(value *EnrollmentConfigApplyConfiguration) *OrdererGroupSpecApplyConfiguration {
	b.Enrollment = value
	return b
}

// WithManageChildCRDs sets the ManageChildCRDs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManageChildCRDs field is set to the value of the last call.
func (b *OrdererGroupSpecApplyConfiguration) WithManageChildCRDs(value bool) *OrdererGroupSpecApplyConfiguration {
	b.ManageChildCRDs = &value
	return b
}
