/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OrdererOrganizationApplyConfiguration represents a declarative configuration of the OrdererOrganization type for use
// with apply.
type OrdererOrganizationApplyConfiguration struct {
	Name          *string                                `json:"name,omitempty"`
	MSPID         *string                                `json:"mspId,omitempty"`
	SignCACertRef *SecretKeyNSSelectorApplyConfiguration `json:"signCaCertRef,omitempty"`
	TLSCACertRef  *SecretKeyNSSelectorApplyConfiguration `json:"tlsCaCertRef,omitempty"`
	AdminCertRef  *SecretKeyNSSelectorApplyConfiguration `json:"adminCertRef,omitempty"`
}

// OrdererOrganizationApplyConfiguration constructs a declarative configuration of the OrdererOrganization type for use with
// apply.
func OrdererOrganization() *OrdererOrganizationApplyConfiguration {
	return &OrdererOrganizationApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *OrdererOrganizationApplyConfiguration) WithName(value string) *OrdererOrganizationApplyConfiguration {
	b.Name = &value
	return b
}

// WithMSPID sets the MSPID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MSPID field is set to the value of the last call.
func (b *OrdererOrganizationApplyConfiguration) WithMSPID(value string) *OrdererOrganizationApplyConfiguration {
	b.MSPID = &value
	return b
}

// WithSignCACertRef sets the SignCACertRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SignCACertRef field is set to the value of the last call.
func (b *OrdererOrganizationApplyConfiguration) WithSignCACertRef(value *SecretKeyNSSelectorApplyConfiguration) *OrdererOrganizationApplyConfiguration {
	b.SignCACertRef = value
	return b
}

// WithTLSCACertRef sets the TLSCACertRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSCACertRef field is set to the value of the last call.
func (b *OrdererOrganizationApplyConfiguration) WithTLSCACertRef(value *SecretKeyNSSelectorApplyConfiguration) *OrdererOrganizationApplyConfiguration {
	b.TLSCACertRef = value
	return b
}

// WithAdminCertRef sets the AdminCertRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminCertRef field is set to the value of the last call.
func (b *OrdererOrganizationApplyConfiguration) WithAdminCertRef(value *SecretKeyNSSelectorApplyConfiguration) *OrdererOrganizationApplyConfiguration {
	b.AdminCertRef = value
	return b
}
