/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// OrdererBatcherSpecApplyConfiguration represents a declarative configuration of the OrdererBatcherSpec type for use
// with apply.
type OrdererBatcherSpecApplyConfiguration struct {
	BootstrapMode    *string                             `json:"bootstrapMode,omitempty"`
	MSPID            *string                             `json:"mspid,omitempty"`
	PartyID          *int32                              `json:"partyID,omitempty"`
	ShardID          *int32                              `json:"shardID,omitempty"`
	Image            *string                             `json:"image,omitempty"`
	ImageTag         *string                             `json:"imageTag,omitempty"`
	Genesis          *GenesisConfigApplyConfiguration    `json:"genesis,omitempty"`
	Replicas         *int32                              `json:"replicas,omitempty"`
	Storage          *StorageConfigApplyConfiguration    `json:"storage,omitempty"`
	StorageClassName *string                             `json:"storageClassName,omitempty"`
	PVCAccessModes   []string                            `json:"pvcAccessModes,omitempty"`
	PVCStorageSize   *string                             `json:"pvcStorageSize,omitempty"`
	Resources        *v1.ResourceRequirements            `json:"resources,omitempty"`
	SecurityContext  *SecurityContextApplyConfiguration  `json:"securityContext,omitempty"`
	PodAnnotations   map[string]string                   `json:"podAnnotations,omitempty"`
	PodLabels        map[string]string                   `json:"podLabels,omitempty"`
	Volumes          []VolumeApplyConfiguration          `json:"volumes,omitempty"`
	Affinity         *AffinityApplyConfiguration         `json:"affinity,omitempty"`
	VolumeMounts     []VolumeMountApplyConfiguration     `json:"volumeMounts,omitempty"`
	ImagePullSecrets []ImagePullSecretApplyConfiguration `json:"imagePullSecrets,omitempty"`
	Tolerations      []TolerationApplyConfiguration      `json:"tolerations,omitempty"`
	Ingress          *IngressConfigApplyConfiguration    `json:"ingress,omitempty"`
	Enrollment       *EnrollmentConfigApplyConfiguration `json:"enrollment,omitempty"`
	SANS             *SANSConfigApplyConfiguration       `json:"sans,omitempty"`
	Endpoints        []string                            `json:"endpoints,omitempty"`
	Env              []v1.EnvVar                         `json:"env,omitempty"`
	Command          []string                            `json:"command,omitempty"`
	Args             []string                            `json:"args,omitempty"`
}

// OrdererBatcherSpecApplyConfiguration constructs a declarative configuration of the OrdererBatcherSpec type for use with
// apply.
func OrdererBatcherSpec() *OrdererBatcherSpecApplyConfiguration {
	return &OrdererBatcherSpecApplyConfiguration{}
}

// WithBootstrapMode sets the BootstrapMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootstrapMode field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithBootstrapMode(value string) *OrdererBatcherSpecApplyConfiguration {
	b.BootstrapMode = &value
	return b
}

// WithMSPID sets the MSPID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MSPID field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithMSPID(value string) *OrdererBatcherSpecApplyConfiguration {
	b.MSPID = &value
	return b
}

// WithPartyID sets the PartyID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PartyID field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithPartyID(value int32) *OrdererBatcherSpecApplyConfiguration {
	b.PartyID = &value
	return b
}

// WithShardID sets the ShardID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShardID field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithShardID(value int32) *OrdererBatcherSpecApplyConfiguration {
	b.ShardID = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithImage(value string) *OrdererBatcherSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithImageTag sets the ImageTag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageTag field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithImageTag(value string) *OrdererBatcherSpecApplyConfiguration {
	b.ImageTag = &value
	return b
}

// WithGenesis sets the Genesis field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Genesis field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithGenesis(value *GenesisConfigApplyConfiguration) *OrdererBatcherSpecApplyConfiguration {
	b.Genesis = value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithReplicas(value int32) *OrdererBatcherSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithStorage(value *StorageConfigApplyConfiguration) *OrdererBatcherSpecApplyConfiguration {
	b.Storage = value
	return b
}

// WithStorageClassName sets the StorageClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClassName field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithStorageClassName(value string) *OrdererBatcherSpecApplyConfiguration {
	b.StorageClassName = &value
	return b
}

// WithPVCAccessModes adds the given value to the PVCAccessModes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PVCAccessModes field.
func (b *OrdererBatcherSpecApplyConfiguration) WithPVCAccessModes(values ...string) *OrdererBatcherSpecApplyConfiguration {
	for i := range values {
		b.PVCAccessModes = append(b.PVCAccessModes, values[i])
	}
	return b
}

// WithPVCStorageSize sets the PVCStorageSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PVCStorageSize field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithPVCStorageSize(value string) *OrdererBatcherSpecApplyConfiguration {
	b.PVCStorageSize = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *OrdererBatcherSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithSecurityContext(value *SecurityContextApplyConfiguration) *OrdererBatcherSpecApplyConfiguration {
	b.SecurityContext = value
	return b
}

// WithPodAnnotations puts the entries into the PodAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodAnnotations field,
// overwriting an existing map entries in PodAnnotations field with the same key.
func (b *OrdererBatcherSpecApplyConfiguration) WithPodAnnotations(entries map[string]string) *OrdererBatcherSpecApplyConfiguration {
	if b.PodAnnotations == nil && len(entries) > 0 {
		b.PodAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodAnnotations[k] = v
	}
	return b
}

// WithPodLabels puts the entries into the PodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodLabels field,
// overwriting an existing map entries in PodLabels field with the same key.
func (b *OrdererBatcherSpecApplyConfiguration) WithPodLabels(entries map[string]string) *OrdererBatcherSpecApplyConfiguration {
	if b.PodLabels == nil && len(entries) > 0 {
		b.PodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodLabels[k] = v
	}
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *OrdererBatcherSpecApplyConfiguration) WithVolumes(values ...*VolumeApplyConfiguration) *OrdererBatcherSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumes")
		}
		b.Volumes = append(b.Volumes, *values[i])
	}
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithAffinity(value *AffinityApplyConfiguration) *OrdererBatcherSpecApplyConfiguration {
	b.Affinity = value
	return b
}

// WithVolumeMounts adds the given value to the VolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeMounts field.
func (b *OrdererBatcherSpecApplyConfiguration) WithVolumeMounts(values ...*VolumeMountApplyConfiguration) *OrdererBatcherSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumeMounts")
		}
		b.VolumeMounts = append(b.VolumeMounts, *values[i])
	}
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *OrdererBatcherSpecApplyConfiguration) WithImagePullSecrets(values ...*ImagePullSecretApplyConfiguration) *OrdererBatcherSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithImagePullSecrets")
		}
		b.ImagePullSecrets = append(b.ImagePullSecrets, *values[i])
	}
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *OrdererBatcherSpecApplyConfiguration) WithTolerations(values ...*TolerationApplyConfiguration) *OrdererBatcherSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTolerations")
		}
		b.Tolerations = append(b.Tolerations, *values[i])
	}
	return b
}

// WithIngress sets the Ingress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ingress field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithIngress(value *IngressConfigApplyConfiguration) *OrdererBatcherSpecApplyConfiguration {
	b.Ingress = value
	return b
}

// WithEnrollment sets the Enrollment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enrollment field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithEnrollment(value *EnrollmentConfigApplyConfiguration) *OrdererBatcherSpecApplyConfiguration {
	b.Enrollment = value
	return b
}

// WithSANS sets the SANS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SANS field is set to the value of the last call.
func (b *OrdererBatcherSpecApplyConfiguration) WithSANS(value *SANSConfigApplyConfiguration) *OrdererBatcherSpecApplyConfiguration {
	b.SANS = value
	return b
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *OrdererBatcherSpecApplyConfiguration) WithEndpoints(values ...string) *OrdererBatcherSpecApplyConfiguration {
	for i := range values {
		b.Endpoints = append(b.Endpoints, values[i])
	}
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *OrdererBatcherSpecApplyConfiguration) WithEnv(values ...v1.EnvVar) *OrdererBatcherSpecApplyConfiguration {
	for i := range values {
		b.Env = append(b.Env, values[i])
	}
	return b
}

// WithCommand adds the given value to the Command field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Command field.
func (b *OrdererBatcherSpecApplyConfiguration) WithCommand(values ...string) *OrdererBatcherSpecApplyConfiguration {
	for i := range values {
		b.Command = append(b.Command, values[i])
	}
	return b
}

// WithArgs adds the given value to the Args field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Args field.
func (b *OrdererBatcherSpecApplyConfiguration) WithArgs(values ...string) *OrdererBatcherSpecApplyConfiguration {
	for i := range values {
		b.Args = append(b.Args, values[i])
	}
	return b
}
