/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// P2POptionsApplyConfiguration represents a declarative configuration of the P2POptions type for use
// with apply.
type P2POptionsApplyConfiguration struct {
	Routing *RoutingConfigApplyConfiguration `json:"routing,omitempty"`
}

// P2POptionsApplyConfiguration constructs a declarative configuration of the P2POptions type for use with
// apply.
func P2POptions() *P2POptionsApplyConfiguration {
	return &P2POptionsApplyConfiguration{}
}

// WithRouting sets the Routing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Routing field is set to the value of the last call.
func (b *P2POptionsApplyConfiguration) WithRouting(value *RoutingConfigApplyConfiguration) *P2POptionsApplyConfiguration {
	b.Routing = value
	return b
}
