/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PartyRouterConfigApplyConfiguration represents a declarative configuration of the PartyRouterConfig type for use
// with apply.
type PartyRouterConfigApplyConfiguration struct {
	Host    *string                                `json:"host,omitempty"`
	Port    *int32                                 `json:"port,omitempty"`
	TLSCert *SecretKeyNSSelectorApplyConfiguration `json:"tlsCert,omitempty"`
}

// PartyRouterConfigApplyConfiguration constructs a declarative configuration of the PartyRouterConfig type for use with
// apply.
func PartyRouterConfig() *PartyRouterConfigApplyConfiguration {
	return &PartyRouterConfigApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *PartyRouterConfigApplyConfiguration) WithHost(value string) *PartyRouterConfigApplyConfiguration {
	b.Host = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *PartyRouterConfigApplyConfiguration) WithPort(value int32) *PartyRouterConfigApplyConfiguration {
	b.Port = &value
	return b
}

// WithTLSCert sets the TLSCert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSCert field is set to the value of the last call.
func (b *PartyRouterConfigApplyConfiguration) WithTLSCert(value *SecretKeyNSSelectorApplyConfiguration) *PartyRouterConfigApplyConfiguration {
	b.TLSCert = value
	return b
}
