/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PartyConfigApplyConfiguration represents a declarative configuration of the PartyConfig type for use
// with apply.
type PartyConfigApplyConfiguration struct {
	PartyID         *int32                                  `json:"partyID,omitempty"`
	CACerts         []SecretKeyNSSelectorApplyConfiguration `json:"caCerts,omitempty"`
	TLSCACerts      []SecretKeyNSSelectorApplyConfiguration `json:"tlsCaCerts,omitempty"`
	RouterConfig    *PartyRouterConfigApplyConfiguration    `json:"routerConfig,omitempty"`
	BatchersConfig  []PartyBatcherConfigApplyConfiguration  `json:"batchersConfig,omitempty"`
	ConsenterConfig *PartyConsenterConfigApplyConfiguration `json:"consenterConfig,omitempty"`
	AssemblerConfig *PartyAssemblerConfigApplyConfiguration `json:"assemblerConfig,omitempty"`
}

// PartyConfigApplyConfiguration constructs a declarative configuration of the PartyConfig type for use with
// apply.
func PartyConfig() *PartyConfigApplyConfiguration {
	return &PartyConfigApplyConfiguration{}
}

// WithPartyID sets the PartyID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PartyID field is set to the value of the last call.
func (b *PartyConfigApplyConfiguration) WithPartyID(value int32) *PartyConfigApplyConfiguration {
	b.PartyID = &value
	return b
}

// WithCACerts adds the given value to the CACerts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CACerts field.
func (b *PartyConfigApplyConfiguration) WithCACerts(values ...*SecretKeyNSSelectorApplyConfiguration) *PartyConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCACerts")
		}
		b.CACerts = append(b.CACerts, *values[i])
	}
	return b
}

// WithTLSCACerts adds the given value to the TLSCACerts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TLSCACerts field.
func (b *PartyConfigApplyConfiguration) WithTLSCACerts(values ...*SecretKeyNSSelectorApplyConfiguration) *PartyConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTLSCACerts")
		}
		b.TLSCACerts = append(b.TLSCACerts, *values[i])
	}
	return b
}

// WithRouterConfig sets the RouterConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RouterConfig field is set to the value of the last call.
func (b *PartyConfigApplyConfiguration) WithRouterConfig(value *PartyRouterConfigApplyConfiguration) *PartyConfigApplyConfiguration {
	b.RouterConfig = value
	return b
}

// WithBatchersConfig adds the given value to the BatchersConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BatchersConfig field.
func (b *PartyConfigApplyConfiguration) WithBatchersConfig(values ...*PartyBatcherConfigApplyConfiguration) *PartyConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBatchersConfig")
		}
		b.BatchersConfig = append(b.BatchersConfig, *values[i])
	}
	return b
}

// WithConsenterConfig sets the ConsenterConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsenterConfig field is set to the value of the last call.
func (b *PartyConfigApplyConfiguration) WithConsenterConfig(value *PartyConsenterConfigApplyConfiguration) *PartyConfigApplyConfiguration {
	b.ConsenterConfig = value
	return b
}

// WithAssemblerConfig sets the AssemblerConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AssemblerConfig field is set to the value of the last call.
func (b *PartyConfigApplyConfiguration) WithAssemblerConfig(value *PartyAssemblerConfigApplyConfiguration) *PartyConfigApplyConfiguration {
	b.AssemblerConfig = value
	return b
}
