/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PostgreSQLConfigApplyConfiguration represents a declarative configuration of the PostgreSQLConfig type for use
// with apply.
type PostgreSQLConfigApplyConfiguration struct {
	Host           *string                                  `json:"host,omitempty"`
	Port           *int32                                   `json:"port,omitempty"`
	Database       *string                                  `json:"database,omitempty"`
	Username       *string                                  `json:"username,omitempty"`
	PasswordSecret *SecretRefApplyConfiguration             `json:"passwordSecret,omitempty"`
	MaxConnections *int32                                   `json:"maxConnections,omitempty"`
	MinConnections *int32                                   `json:"minConnections,omitempty"`
	LoadBalance    *bool                                    `json:"loadBalance,omitempty"`
	Retry          *PostgreSQLRetryConfigApplyConfiguration `json:"retry,omitempty"`
}

// PostgreSQLConfigApplyConfiguration constructs a declarative configuration of the PostgreSQLConfig type for use with
// apply.
func PostgreSQLConfig() *PostgreSQLConfigApplyConfiguration {
	return &PostgreSQLConfigApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *PostgreSQLConfigApplyConfiguration) WithHost(value string) *PostgreSQLConfigApplyConfiguration {
	b.Host = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *PostgreSQLConfigApplyConfiguration) WithPort(value int32) *PostgreSQLConfigApplyConfiguration {
	b.Port = &value
	return b
}

// WithDatabase sets the Database field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Database field is set to the value of the last call.
func (b *PostgreSQLConfigApplyConfiguration) WithDatabase(value string) *PostgreSQLConfigApplyConfiguration {
	b.Database = &value
	return b
}

// WithUsername sets the Username field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Username field is set to the value of the last call.
func (b *PostgreSQLConfigApplyConfiguration) WithUsername(value string) *PostgreSQLConfigApplyConfiguration {
	b.Username = &value
	return b
}

// WithPasswordSecret sets the PasswordSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PasswordSecret field is set to the value of the last call.
func (b *PostgreSQLConfigApplyConfiguration) WithPasswordSecret(value *SecretRefApplyConfiguration) *PostgreSQLConfigApplyConfiguration {
	b.PasswordSecret = value
	return b
}

// WithMaxConnections sets the MaxConnections field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxConnections field is set to the value of the last call.
func (b *PostgreSQLConfigApplyConfiguration) WithMaxConnections(value int32) *PostgreSQLConfigApplyConfiguration {
	b.MaxConnections = &value
	return b
}

// WithMinConnections sets the MinConnections field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinConnections field is set to the value of the last call.
func (b *PostgreSQLConfigApplyConfiguration) WithMinConnections(value int32) *PostgreSQLConfigApplyConfiguration {
	b.MinConnections = &value
	return b
}

// WithLoadBalance sets the LoadBalance field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadBalance field is set to the value of the last call.
func (b *PostgreSQLConfigApplyConfiguration) WithLoadBalance(value bool) *PostgreSQLConfigApplyConfiguration {
	b.LoadBalance = &value
	return b
}

// WithRetry sets the Retry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retry field is set to the value of the last call.
func (b *PostgreSQLConfigApplyConfiguration) WithRetry(value *PostgreSQLRetryConfigApplyConfiguration) *PostgreSQLConfigApplyConfiguration {
	b.Retry = value
	return b
}
