/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PublicParametersConfigApplyConfiguration represents a declarative configuration of the PublicParametersConfig type for use
// with apply.
type PublicParametersConfigApplyConfiguration struct {
	Path *string `json:"path,omitempty"`
}

// PublicParametersConfigApplyConfiguration constructs a declarative configuration of the PublicParametersConfig type for use with
// apply.
func PublicParametersConfig() *PublicParametersConfigApplyConfiguration {
	return &PublicParametersConfigApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *PublicParametersConfigApplyConfiguration) WithPath(value string) *PublicParametersConfigApplyConfiguration {
	b.Path = &value
	return b
}
