/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// QueryServiceConfigApplyConfiguration represents a declarative configuration of the QueryServiceConfig type for use
// with apply.
type QueryServiceConfigApplyConfiguration struct {
	Address *string `json:"address,omitempty"`
}

// QueryServiceConfigApplyConfiguration constructs a declarative configuration of the QueryServiceConfig type for use with
// apply.
func QueryServiceConfig() *QueryServiceConfigApplyConfiguration {
	return &QueryServiceConfigApplyConfiguration{}
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *QueryServiceConfigApplyConfiguration) WithAddress(value string) *QueryServiceConfigApplyConfiguration {
	b.Address = &value
	return b
}
