/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RoutingConfigApplyConfiguration represents a declarative configuration of the RoutingConfig type for use
// with apply.
type RoutingConfigApplyConfiguration struct {
	Path   *string               `json:"path,omitempty"`
	Inline *runtime.RawExtension `json:"inline,omitempty"`
}

// RoutingConfigApplyConfiguration constructs a declarative configuration of the RoutingConfig type for use with
// apply.
func RoutingConfig() *RoutingConfigApplyConfiguration {
	return &RoutingConfigApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *RoutingConfigApplyConfiguration) WithPath(value string) *RoutingConfigApplyConfiguration {
	b.Path = &value
	return b
}

// WithInline sets the Inline field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Inline field is set to the value of the last call.
func (b *RoutingConfigApplyConfiguration) WithInline(value runtime.RawExtension) *RoutingConfigApplyConfiguration {
	b.Inline = &value
	return b
}
