/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SANSConfigApplyConfiguration represents a declarative configuration of the SANSConfig type for use
// with apply.
type SANSConfigApplyConfiguration struct {
	DNSNames    []string `json:"dnsNames,omitempty"`
	IPAddresses []string `json:"ipAddresses,omitempty"`
}

// SANSConfigApplyConfiguration constructs a declarative configuration of the SANSConfig type for use with
// apply.
func SANSConfig() *SANSConfigApplyConfiguration {
	return &SANSConfigApplyConfiguration{}
}

// WithDNSNames adds the given value to the DNSNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DNSNames field.
func (b *SANSConfigApplyConfiguration) WithDNSNames(values ...string) *SANSConfigApplyConfiguration {
	for i := range values {
		b.DNSNames = append(b.DNSNames, values[i])
	}
	return b
}

// WithIPAddresses adds the given value to the IPAddresses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPAddresses field.
func (b *SANSConfigApplyConfiguration) WithIPAddresses(values ...string) *SANSConfigApplyConfiguration {
	for i := range values {
		b.IPAddresses = append(b.IPAddresses, values[i])
	}
	return b
}
