/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SmartBFTConfigApplyConfiguration represents a declarative configuration of the SmartBFTConfig type for use
// with apply.
type SmartBFTConfigApplyConfiguration struct {
	SelfID                        *int32  `json:"selfID,omitempty"`
	RequestBatchMaxCount          *int32  `json:"requestBatchMaxCount,omitempty"`
	RequestBatchMaxBytes          *int32  `json:"requestBatchMaxBytes,omitempty"`
	RequestBatchMaxInterval       *string `json:"requestBatchMaxInterval,omitempty"`
	IncomingMessageBufferSize     *int32  `json:"incomingMessageBufferSize,omitempty"`
	RequestPoolSize               *int32  `json:"requestPoolSize,omitempty"`
	RequestForwardTimeout         *string `json:"requestForwardTimeout,omitempty"`
	RequestComplainTimeout        *string `json:"requestComplainTimeout,omitempty"`
	RequestAutoRemoveTimeout      *string `json:"requestAutoRemoveTimeout,omitempty"`
	ViewChangeResendInterval      *string `json:"viewChangeResendInterval,omitempty"`
	ViewChangeTimeout             *string `json:"viewChangeTimeout,omitempty"`
	LeaderHeartbeatTimeout        *string `json:"leaderHeartbeatTimeout,omitempty"`
	LeaderHeartbeatCount          *int32  `json:"leaderHeartbeatCount,omitempty"`
	NumOfTicksBehindBeforeSyncing *int32  `json:"numOfTicksBehindBeforeSyncing,omitempty"`
	CollectTimeout                *string `json:"collectTimeout,omitempty"`
	SyncOnStart                   *bool   `json:"syncOnStart,omitempty"`
	SpeedUpViewChange             *bool   `json:"speedUpViewChange,omitempty"`
	LeaderRotation                *bool   `json:"leaderRotation,omitempty"`
	DecisionsPerLeader            *int32  `json:"decisionsPerLeader,omitempty"`
	RequestMaxBytes               *int32  `json:"requestMaxBytes,omitempty"`
	RequestPoolSubmitTimeout      *string `json:"requestPoolSubmitTimeout,omitempty"`
}

// SmartBFTConfigApplyConfiguration constructs a declarative configuration of the SmartBFTConfig type for use with
// apply.
func SmartBFTConfig() *SmartBFTConfigApplyConfiguration {
	return &SmartBFTConfigApplyConfiguration{}
}

// WithSelfID sets the SelfID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SelfID field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithSelfID(value int32) *SmartBFTConfigApplyConfiguration {
	b.SelfID = &value
	return b
}

// WithRequestBatchMaxCount sets the RequestBatchMaxCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestBatchMaxCount field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithRequestBatchMaxCount(value int32) *SmartBFTConfigApplyConfiguration {
	b.RequestBatchMaxCount = &value
	return b
}

// WithRequestBatchMaxBytes sets the RequestBatchMaxBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestBatchMaxBytes field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithRequestBatchMaxBytes(value int32) *SmartBFTConfigApplyConfiguration {
	b.RequestBatchMaxBytes = &value
	return b
}

// WithRequestBatchMaxInterval sets the RequestBatchMaxInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestBatchMaxInterval field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithRequestBatchMaxInterval(value string) *SmartBFTConfigApplyConfiguration {
	b.RequestBatchMaxInterval = &value
	return b
}

// WithIncomingMessageBufferSize sets the IncomingMessageBufferSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IncomingMessageBufferSize field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithIncomingMessageBufferSize(value int32) *SmartBFTConfigApplyConfiguration {
	b.IncomingMessageBufferSize = &value
	return b
}

// WithRequestPoolSize sets the RequestPoolSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestPoolSize field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithRequestPoolSize(value int32) *SmartBFTConfigApplyConfiguration {
	b.RequestPoolSize = &value
	return b
}

// WithRequestForwardTimeout sets the RequestForwardTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestForwardTimeout field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithRequestForwardTimeout(value string) *SmartBFTConfigApplyConfiguration {
	b.RequestForwardTimeout = &value
	return b
}

// WithRequestComplainTimeout sets the RequestComplainTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestComplainTimeout field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithRequestComplainTimeout(value string) *SmartBFTConfigApplyConfiguration {
	b.RequestComplainTimeout = &value
	return b
}

// WithRequestAutoRemoveTimeout sets the RequestAutoRemoveTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestAutoRemoveTimeout field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithRequestAutoRemoveTimeout(value string) *SmartBFTConfigApplyConfiguration {
	b.RequestAutoRemoveTimeout = &value
	return b
}

// WithViewChangeResendInterval sets the ViewChangeResendInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ViewChangeResendInterval field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithViewChangeResendInterval(value string) *SmartBFTConfigApplyConfiguration {
	b.ViewChangeResendInterval = &value
	return b
}

// WithViewChangeTimeout sets the ViewChangeTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ViewChangeTimeout field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithViewChangeTimeout(value string) *SmartBFTConfigApplyConfiguration {
	b.ViewChangeTimeout = &value
	return b
}

// WithLeaderHeartbeatTimeout sets the LeaderHeartbeatTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaderHeartbeatTimeout field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithLeaderHeartbeatTimeout(value string) *SmartBFTConfigApplyConfiguration {
	b.LeaderHeartbeatTimeout = &value
	return b
}

// WithLeaderHeartbeatCount sets the LeaderHeartbeatCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaderHeartbeatCount field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithLeaderHeartbeatCount(value int32) *SmartBFTConfigApplyConfiguration {
	b.LeaderHeartbeatCount = &value
	return b
}

// WithNumOfTicksBehindBeforeSyncing sets the NumOfTicksBehindBeforeSyncing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NumOfTicksBehindBeforeSyncing field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithNumOfTicksBehindBeforeSyncing(value int32) *SmartBFTConfigApplyConfiguration {
	b.NumOfTicksBehindBeforeSyncing = &value
	return b
}

// WithCollectTimeout sets the CollectTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollectTimeout field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithCollectTimeout(value string) *SmartBFTConfigApplyConfiguration {
	b.CollectTimeout = &value
	return b
}

// WithSyncOnStart sets the SyncOnStart field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SyncOnStart field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithSyncOnStart(value bool) *SmartBFTConfigApplyConfiguration {
	b.SyncOnStart = &value
	return b
}

// WithSpeedUpViewChange sets the SpeedUpViewChange field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SpeedUpViewChange field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithSpeedUpViewChange(value bool) *SmartBFTConfigApplyConfiguration {
	b.SpeedUpViewChange = &value
	return b
}

// WithLeaderRotation sets the LeaderRotation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaderRotation field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithLeaderRotation(value bool) *SmartBFTConfigApplyConfiguration {
	b.LeaderRotation = &value
	return b
}

// WithDecisionsPerLeader sets the DecisionsPerLeader field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DecisionsPerLeader field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithDecisionsPerLeader(value int32) *SmartBFTConfigApplyConfiguration {
	b.DecisionsPerLeader = &value
	return b
}

// WithRequestMaxBytes sets the RequestMaxBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestMaxBytes field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithRequestMaxBytes(value int32) *SmartBFTConfigApplyConfiguration {
	b.RequestMaxBytes = &value
	return b
}

// WithRequestPoolSubmitTimeout sets the RequestPoolSubmitTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestPoolSubmitTimeout field is set to the value of the last call.
func (b *SmartBFTConfigApplyConfiguration) WithRequestPoolSubmitTimeout(value string) *SmartBFTConfigApplyConfiguration {
	b.RequestPoolSubmitTimeout = &value
	return b
}
