/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// StorageConfigApplyConfiguration represents a declarative configuration of the StorageConfig type for use
// with apply.
type StorageConfigApplyConfiguration struct {
	PVCName      *string `json:"pvcName,omitempty"`
	StorageClass *string `json:"storageClass,omitempty"`
	Size         *string `json:"size,omitempty"`
	AccessMode   *string `json:"accessMode,omitempty"`
}

// StorageConfigApplyConfiguration constructs a declarative configuration of the StorageConfig type for use with
// apply.
func StorageConfig() *StorageConfigApplyConfiguration {
	return &StorageConfigApplyConfiguration{}
}

// WithPVCName sets the PVCName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PVCName field is set to the value of the last call.
func (b *StorageConfigApplyConfiguration) WithPVCName(value string) *StorageConfigApplyConfiguration {
	b.PVCName = &value
	return b
}

// WithStorageClass sets the StorageClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClass field is set to the value of the last call.
func (b *StorageConfigApplyConfiguration) WithStorageClass(value string) *StorageConfigApplyConfiguration {
	b.StorageClass = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *StorageConfigApplyConfiguration) WithSize(value string) *StorageConfigApplyConfiguration {
	b.Size = &value
	return b
}

// WithAccessMode sets the AccessMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessMode field is set to the value of the last call.
func (b *StorageConfigApplyConfiguration) WithAccessMode(value string) *StorageConfigApplyConfiguration {
	b.AccessMode = &value
	return b
}
