/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TMSServicesApplyConfiguration represents a declarative configuration of the TMSServices type for use
// with apply.
type TMSServicesApplyConfiguration struct {
	Network *NetworkServiceConfigApplyConfiguration `json:"network,omitempty"`
}

// TMSServicesApplyConfiguration constructs a declarative configuration of the TMSServices type for use with
// apply.
func TMSServices() *TMSServicesApplyConfiguration {
	return &TMSServicesApplyConfiguration{}
}

// WithNetwork sets the Network field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Network field is set to the value of the last call.
func (b *TMSServicesApplyConfiguration) WithNetwork(value *NetworkServiceConfigApplyConfiguration) *TMSServicesApplyConfiguration {
	b.Network = value
	return b
}
