/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ValidatorComponentConfigApplyConfiguration represents a declarative configuration of the ValidatorComponentConfig type for use
// with apply.
type ValidatorComponentConfigApplyConfiguration struct {
	CommonComponentConfigApplyConfiguration `json:",inline"`
	Ingress                                 *IngressConfigApplyConfiguration    `json:"ingress,omitempty"`
	Enrollment                              *EnrollmentConfigApplyConfiguration `json:"enrollment,omitempty"`
	SANS                                    *SANSConfigApplyConfiguration       `json:"sans,omitempty"`
	Endpoints                               []string                            `json:"endpoints,omitempty"`
	Env                                     []v1.EnvVar                         `json:"env,omitempty"`
	Command                                 []string                            `json:"command,omitempty"`
	Args                                    []string                            `json:"args,omitempty"`
	PostgreSQL                              *PostgreSQLConfigApplyConfiguration `json:"postgresql,omitempty"`
}

// ValidatorComponentConfigApplyConfiguration constructs a declarative configuration of the ValidatorComponentConfig type for use with
// apply.
func ValidatorComponentConfig() *ValidatorComponentConfigApplyConfiguration {
	return &ValidatorComponentConfigApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ValidatorComponentConfigApplyConfiguration) WithReplicas(value int32) *ValidatorComponentConfigApplyConfiguration {
	b.CommonComponentConfigApplyConfiguration.Replicas = &value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *ValidatorComponentConfigApplyConfiguration) WithStorage(value *StorageConfigApplyConfiguration) *ValidatorComponentConfigApplyConfiguration {
	b.CommonComponentConfigApplyConfiguration.Storage = value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *ValidatorComponentConfigApplyConfiguration) WithResources(value v1.ResourceRequirements) *ValidatorComponentConfigApplyConfiguration {
	b.CommonComponentConfigApplyConfiguration.Resources = &value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *ValidatorComponentConfigApplyConfiguration) WithSecurityContext(value *SecurityContextApplyConfiguration) *ValidatorComponentConfigApplyConfiguration {
	b.CommonComponentConfigApplyConfiguration.SecurityContext = value
	return b
}

// WithPodAnnotations puts the entries into the PodAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodAnnotations field,
// overwriting an existing map entries in PodAnnotations field with the same key.
func (b *ValidatorComponentConfigApplyConfiguration) WithPodAnnotations(entries map[string]string) *ValidatorComponentConfigApplyConfiguration {
	if b.CommonComponentConfigApplyConfiguration.PodAnnotations == nil && len(entries) > 0 {
		b.CommonComponentConfigApplyConfiguration.PodAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.CommonComponentConfigApplyConfiguration.PodAnnotations[k] = v
	}
	return b
}

// WithPodLabels puts the entries into the PodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodLabels field,
// overwriting an existing map entries in PodLabels field with the same key.
func (b *ValidatorComponentConfigApplyConfiguration) WithPodLabels(entries map[string]string) *ValidatorComponentConfigApplyConfiguration {
	if b.CommonComponentConfigApplyConfiguration.PodLabels == nil && len(entries) > 0 {
		b.CommonComponentConfigApplyConfiguration.PodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.CommonComponentConfigApplyConfiguration.PodLabels[k] = v
	}
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *ValidatorComponentConfigApplyConfiguration) WithVolumes(values ...*VolumeApplyConfiguration) *ValidatorComponentConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumes")
		}
		b.CommonComponentConfigApplyConfiguration.Volumes = append(b.CommonComponentConfigApplyConfiguration.Volumes, *values[i])
	}
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *ValidatorComponentConfigApplyConfiguration) WithAffinity(value *AffinityApplyConfiguration) *ValidatorComponentConfigApplyConfiguration {
	b.CommonComponentConfigApplyConfiguration.Affinity = value
	return b
}

// WithVolumeMounts adds the given value to the VolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeMounts field.
func (b *ValidatorComponentConfigApplyConfiguration) WithVolumeMounts(values ...*VolumeMountApplyConfiguration) *ValidatorComponentConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumeMounts")
		}
		b.CommonComponentConfigApplyConfiguration.VolumeMounts = append(b.CommonComponentConfigApplyConfiguration.VolumeMounts, *values[i])
	}
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *ValidatorComponentConfigApplyConfiguration) WithImagePullSecrets(values ...*ImagePullSecretApplyConfiguration) *ValidatorComponentConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithImagePullSecrets")
		}
		b.CommonComponentConfigApplyConfiguration.ImagePullSecrets = append(b.CommonComponentConfigApplyConfiguration.ImagePullSecrets, *values[i])
	}
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *ValidatorComponentConfigApplyConfiguration) WithTolerations(values ...*TolerationApplyConfiguration) *ValidatorComponentConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTolerations")
		}
		b.CommonComponentConfigApplyConfiguration.Tolerations = append(b.CommonComponentConfigApplyConfiguration.Tolerations, *values[i])
	}
	return b
}

// WithIngress sets the Ingress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ingress field is set to the value of the last call.
func (b *ValidatorComponentConfigApplyConfiguration) WithIngress(value *IngressConfigApplyConfiguration) *ValidatorComponentConfigApplyConfiguration {
	b.Ingress = value
	return b
}

// WithEnrollment sets the Enrollment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enrollment field is set to the value of the last call.
func (b *ValidatorComponentConfigApplyConfiguration) WithEnrollment(value *EnrollmentConfigApplyConfiguration) *ValidatorComponentConfigApplyConfiguration {
	b.Enrollment = value
	return b
}

// WithSANS sets the SANS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SANS field is set to the value of the last call.
func (b *ValidatorComponentConfigApplyConfiguration) WithSANS(value *SANSConfigApplyConfiguration) *ValidatorComponentConfigApplyConfiguration {
	b.SANS = value
	return b
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *ValidatorComponentConfigApplyConfiguration) WithEndpoints(values ...string) *ValidatorComponentConfigApplyConfiguration {
	for i := range values {
		b.Endpoints = append(b.Endpoints, values[i])
	}
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *ValidatorComponentConfigApplyConfiguration) WithEnv(values ...v1.EnvVar) *ValidatorComponentConfigApplyConfiguration {
	for i := range values {
		b.Env = append(b.Env, values[i])
	}
	return b
}

// WithCommand adds the given value to the Command field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Command field.
func (b *ValidatorComponentConfigApplyConfiguration) WithCommand(values ...string) *ValidatorComponentConfigApplyConfiguration {
	for i := range values {
		b.Command = append(b.Command, values[i])
	}
	return b
}

// WithArgs adds the given value to the Args field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Args field.
func (b *ValidatorComponentConfigApplyConfiguration) WithArgs(values ...string) *ValidatorComponentConfigApplyConfiguration {
	for i := range values {
		b.Args = append(b.Args, values[i])
	}
	return b
}

// WithPostgreSQL sets the PostgreSQL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PostgreSQL field is set to the value of the last call.
func (b *ValidatorComponentConfigApplyConfiguration) WithPostgreSQL(value *PostgreSQLConfigApplyConfiguration) *ValidatorComponentConfigApplyConfiguration {
	b.PostgreSQL = value
	return b
}
