/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	fmt "fmt"

	v1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=fabricx.kfsoft.tech, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("cas"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Fabricx().V1alpha1().CAs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("caenrollments"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Fabricx().V1alpha1().CAEnrollments().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("chainnamespaces"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Fabricx().V1alpha1().ChainNamespaces().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("committers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Fabricx().V1alpha1().Committers().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("endorsers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Fabricx().V1alpha1().Endorsers().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("genesises"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Fabricx().V1alpha1().Genesises().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("identities"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Fabricx().V1alpha1().Identities().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ordererassemblers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Fabricx().V1alpha1().OrdererAssemblers().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ordererbatchers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Fabricx().V1alpha1().OrdererBatchers().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ordererconsenters"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Fabricx().V1alpha1().OrdererConsenters().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("orderergroups"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Fabricx().V1alpha1().OrdererGroups().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ordererrouters"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Fabricx().V1alpha1().OrdererRouters().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
