services:
  endorser2:
    <<: *service-template
    hostname: endorser2.example.com
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_TYPE: endorser
        PLATFORM: "${PLATFORM:-fabricx}"
    volumes:
      - ./${CONF_ROOT:-conf}/endorser2:/conf
    expose:
      - 9401:9001
    ports:
      - 9400:9000/tcp
