apiVersion: fabricx.kfsoft.tech/v1alpha1
kind: Genesis
metadata:
  name: shared-genesis
  namespace: default

spec:
  applicationOrgs:
    - mspId: Org1MSP
      name: Org1MSP
      signCaCertRef:
        key: certfile
        name: test-ca2-msp-crypto
        namespace: default
      tlsCaCertRef:
        key: certfile
        name: test-ca2-tlsca-crypto
        namespace: default
  channelID: arma
  configTemplate:
    configMapName: fabricx-config-template
    key: configtx.yaml
  consenters:
    - clientTlsCertRef:
        key: cert.pem
        name: orderergroup-sample-consenter-tls-cert
        namespace: default
      host: consenter-1-org1.localho.st
      id: 1
      identityRef:
        key: cert.pem
        name: orderergroup-sample-consenter-sign-cert
        namespace: default
      mspId: OrdererMSP
      port: 443
      serverTlsCertRef:
        key: cert.pem
        name: orderergroup-sample-consenter-tls-cert
        namespace: default
    - clientTlsCertRef:
        key: cert.pem
        name: orderergroup-party2-consenter-tls-cert
        namespace: default
      host: consenter-1-org2.localho.st
      id: 2
      identityRef:
        key: cert.pem
        name: orderergroup-party2-consenter-sign-cert
        namespace: default
      mspId: OrdererMSP
      port: 443
      serverTlsCertRef:
        key: cert.pem
        name: orderergroup-party2-consenter-tls-cert
        namespace: default
    - clientTlsCertRef:
        key: cert.pem
        name: orderergroup-party3-consenter-tls-cert
        namespace: default
      host: consenter-1-org3.localho.st
      id: 3
      identityRef:
        key: cert.pem
        name: orderergroup-party3-consenter-sign-cert
        namespace: default
      mspId: OrdererMSP
      port: 443
      serverTlsCertRef:
        key: cert.pem
        name: orderergroup-party3-consenter-tls-cert
        namespace: default
    - clientTlsCertRef:
        key: cert.pem
        name: orderergroup-party4-consenter-tls-cert
        namespace: default
      host: consenter-1-org4.localho.st
      id: 4
      identityRef:
        key: cert.pem
        name: orderergroup-party4-consenter-sign-cert
        namespace: default
      mspId: OrdererMSP
      port: 443
      serverTlsCertRef:
        key: cert.pem
        name: orderergroup-party4-consenter-tls-cert
        namespace: default
  ordererOrganizations:
    - mspId: OrdererMSP
      name: OrdererMSP
      signCaCertRef:
        key: certfile
        name: test-ca2-msp-crypto
        namespace: default
      tlsCaCertRef:
        key: certfile
        name: test-ca2-tlsca-crypto
        namespace: default
      router:
        host: router-org1.localho.st
        port: 443
        partyID: 1
        signCertRef:
          key: cert.pem
          name: router-orderer-sign-cert
          namespace: default
        tlsCertRef:
          key: cert.pem
          name: router-orderer-tls-cert
          namespace: default
      batchers:
        - shardID: 1
          host: batcher-1-org1.localho.st
          port: 443
          signCertRef:
            key: cert.pem
            name: batcher1-orderer-sign-cert
            namespace: default
          tlsCertRef:
            key: cert.pem
            name: batcher1-orderer-tls-cert
            namespace: default
        - shardID: 2
          host: batcher-2-org1.localho.st
          port: 443
          signCertRef:
            key: cert.pem
            name: batcher2-orderer-sign-cert
            namespace: default
          tlsCertRef:
            key: cert.pem
            name: batcher2-orderer-tls-cert
            namespace: default
      consenter:
        host: consenter-1-org1.localho.st
        port: 443
        signCertRef:
          key: cert.pem
          name: consenter-orderer-sign-cert
          namespace: default
        tlsCertRef:
          key: cert.pem
          name: consenter-orderer-tls-cert
          namespace: default
      assembler:
        host: assembler-org1.localho.st
        port: 443
        tlsCertRef:
          key: cert.pem
          name: assembler-orderer-tls-cert
          namespace: default
  output:
    blockKey: genesis.block
    secretName: fabricx-shared-genesis
