# This rule is not used by the project fabric-x-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the fabricx.kfsoft.tech.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fabric-x-operator
    app.kubernetes.io/managed-by: kustomize
  name: committerverifier-editor-role
rules:
- apiGroups:
  - fabricx.kfsoft.tech
  resources:
  - committerverifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fabricx.kfsoft.tech
  resources:
  - committerverifiers/status
  verbs:
  - get
