---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fabricx.kfsoft.tech
  resources:
  - cas
  - committercoordinators
  - committerqueryservices
  - committers
  - committersidecars
  - committervalidators
  - committerverifiers
  - endorsers
  - geneses
  - ordererassemblers
  - ordererbatchers
  - ordererconsenters
  - orderergroups
  - ordererrouters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fabricx.kfsoft.tech
  resources:
  - cas/finalizers
  - committercoordinators/finalizers
  - committerqueryservices/finalizers
  - committers/finalizers
  - committersidecars/finalizers
  - committervalidators/finalizers
  - committerverifiers/finalizers
  - endorsers/finalizers
  - geneses/finalizers
  - ordererassemblers/finalizers
  - ordererbatchers/finalizers
  - ordererconsenters/finalizers
  - ordererrouters/finalizers
  verbs:
  - update
- apiGroups:
  - fabricx.kfsoft.tech
  resources:
  - cas/status
  - committercoordinators/status
  - committerqueryservices/status
  - committers/status
  - committersidecars/status
  - committervalidators/status
  - committerverifiers/status
  - endorsers/status
  - geneses/status
  - ordererassemblers/status
  - ordererbatchers/status
  - ordererconsenters/status
  - orderergroups/status
  - ordererrouters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  - gateways
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
