/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/applyconfiguration/api/v1alpha1"
	typedapiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeChainNamespaces implements ChainNamespaceInterface
type fakeChainNamespaces struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ChainNamespace, *v1alpha1.ChainNamespaceList, *apiv1alpha1.ChainNamespaceApplyConfiguration]
	Fake *FakeFabricxV1alpha1
}

func newFakeChainNamespaces(fake *FakeFabricxV1alpha1) typedapiv1alpha1.ChainNamespaceInterface {
	return &fakeChainNamespaces{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ChainNamespace, *v1alpha1.ChainNamespaceList, *apiv1alpha1.ChainNamespaceApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("chainnamespaces"),
			v1alpha1.SchemeGroupVersion.WithKind("ChainNamespace"),
			func() *v1alpha1.ChainNamespace { return &v1alpha1.ChainNamespace{} },
			func() *v1alpha1.ChainNamespaceList { return &v1alpha1.ChainNamespaceList{} },
			func(dst, src *v1alpha1.ChainNamespaceList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ChainNamespaceList) []*v1alpha1.ChainNamespace {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ChainNamespaceList, items []*v1alpha1.ChainNamespace) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
