/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/applyconfiguration/api/v1alpha1"
	typedapiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEndorsers implements EndorserInterface
type fakeEndorsers struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Endorser, *v1alpha1.EndorserList, *apiv1alpha1.EndorserApplyConfiguration]
	Fake *FakeApiV1alpha1
}

func newFakeEndorsers(fake *FakeApiV1alpha1, namespace string) typedapiv1alpha1.EndorserInterface {
	return &fakeEndorsers{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Endorser, *v1alpha1.EndorserList, *apiv1alpha1.EndorserApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("endorsers"),
			v1alpha1.SchemeGroupVersion.WithKind("Endorser"),
			func() *v1alpha1.Endorser { return &v1alpha1.Endorser{} },
			func() *v1alpha1.EndorserList { return &v1alpha1.EndorserList{} },
			func(dst, src *v1alpha1.EndorserList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.EndorserList) []*v1alpha1.Endorser { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.EndorserList, items []*v1alpha1.Endorser) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
