/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/applyconfiguration/api/v1alpha1"
	typedapiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeOrdererConsenters implements OrdererConsenterInterface
type fakeOrdererConsenters struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.OrdererConsenter, *v1alpha1.OrdererConsenterList, *apiv1alpha1.OrdererConsenterApplyConfiguration]
	Fake *FakeFabricxV1alpha1
}

func newFakeOrdererConsenters(fake *FakeFabricxV1alpha1, namespace string) typedapiv1alpha1.OrdererConsenterInterface {
	return &fakeOrdererConsenters{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.OrdererConsenter, *v1alpha1.OrdererConsenterList, *apiv1alpha1.OrdererConsenterApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("ordererconsenters"),
			v1alpha1.SchemeGroupVersion.WithKind("OrdererConsenter"),
			func() *v1alpha1.OrdererConsenter { return &v1alpha1.OrdererConsenter{} },
			func() *v1alpha1.OrdererConsenterList { return &v1alpha1.OrdererConsenterList{} },
			func(dst, src *v1alpha1.OrdererConsenterList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.OrdererConsenterList) []*v1alpha1.OrdererConsenter {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.OrdererConsenterList, items []*v1alpha1.OrdererConsenter) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
