/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/applyconfiguration/api/v1alpha1"
	typedapiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIdentities implements IdentityInterface
type fakeIdentities struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Identity, *v1alpha1.IdentityList, *apiv1alpha1.IdentityApplyConfiguration]
	Fake *FakeFabricxV1alpha1
}

func newFakeIdentities(fake *FakeFabricxV1alpha1, namespace string) typedapiv1alpha1.IdentityInterface {
	return &fakeIdentities{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Identity, *v1alpha1.IdentityList, *apiv1alpha1.IdentityApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("identities"),
			v1alpha1.SchemeGroupVersion.WithKind("Identity"),
			func() *v1alpha1.Identity { return &v1alpha1.Identity{} },
			func() *v1alpha1.IdentityList { return &v1alpha1.IdentityList{} },
			func(dst, src *v1alpha1.IdentityList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IdentityList) []*v1alpha1.Identity { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.IdentityList, items []*v1alpha1.Identity) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
