/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/applyconfiguration/api/v1alpha1"
	typedapiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeOrdererAssemblers implements OrdererAssemblerInterface
type fakeOrdererAssemblers struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.OrdererAssembler, *v1alpha1.OrdererAssemblerList, *apiv1alpha1.OrdererAssemblerApplyConfiguration]
	Fake *FakeFabricxV1alpha1
}

func newFakeOrdererAssemblers(fake *FakeFabricxV1alpha1, namespace string) typedapiv1alpha1.OrdererAssemblerInterface {
	return &fakeOrdererAssemblers{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.OrdererAssembler, *v1alpha1.OrdererAssemblerList, *apiv1alpha1.OrdererAssemblerApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("ordererassemblers"),
			v1alpha1.SchemeGroupVersion.WithKind("OrdererAssembler"),
			func() *v1alpha1.OrdererAssembler { return &v1alpha1.OrdererAssembler{} },
			func() *v1alpha1.OrdererAssemblerList { return &v1alpha1.OrdererAssemblerList{} },
			func(dst, src *v1alpha1.OrdererAssemblerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.OrdererAssemblerList) []*v1alpha1.OrdererAssembler {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.OrdererAssemblerList, items []*v1alpha1.OrdererAssembler) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
