/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/applyconfiguration/api/v1alpha1"
	scheme "github.com/kfsoftware/fabric-x-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CAsGetter has a method to return a CAInterface.
// A group's client should implement this interface.
type CAsGetter interface {
	CAs(namespace string) CAInterface
}

// CAInterface has methods to work with CA resources.
type CAInterface interface {
	Create(ctx context.Context, cA *apiv1alpha1.CA, opts v1.CreateOptions) (*apiv1alpha1.CA, error)
	Update(ctx context.Context, cA *apiv1alpha1.CA, opts v1.UpdateOptions) (*apiv1alpha1.CA, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, cA *apiv1alpha1.CA, opts v1.UpdateOptions) (*apiv1alpha1.CA, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.CA, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.CAList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.CA, err error)
	Apply(ctx context.Context, cA *applyconfigurationapiv1alpha1.CAApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.CA, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, cA *applyconfigurationapiv1alpha1.CAApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.CA, err error)
	CAExpansion
}

// cAs implements CAInterface
type cAs struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.CA, *apiv1alpha1.CAList, *applyconfigurationapiv1alpha1.CAApplyConfiguration]
}

// newCAs returns a CAs
func newCAs(c *ApiV1alpha1Client, namespace string) *cAs {
	return &cAs{
		gentype.NewClientWithListAndApply[*apiv1alpha1.CA, *apiv1alpha1.CAList, *applyconfigurationapiv1alpha1.CAApplyConfiguration](
			"cas",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.CA { return &apiv1alpha1.CA{} },
			func() *apiv1alpha1.CAList { return &apiv1alpha1.CAList{} },
		),
	}
}
