/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/applyconfiguration/api/v1alpha1"
	scheme "github.com/kfsoftware/fabric-x-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ChainNamespacesGetter has a method to return a ChainNamespaceInterface.
// A group's client should implement this interface.
type ChainNamespacesGetter interface {
	ChainNamespaces() ChainNamespaceInterface
}

// ChainNamespaceInterface has methods to work with ChainNamespace resources.
type ChainNamespaceInterface interface {
	Create(ctx context.Context, chainNamespace *apiv1alpha1.ChainNamespace, opts v1.CreateOptions) (*apiv1alpha1.ChainNamespace, error)
	Update(ctx context.Context, chainNamespace *apiv1alpha1.ChainNamespace, opts v1.UpdateOptions) (*apiv1alpha1.ChainNamespace, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, chainNamespace *apiv1alpha1.ChainNamespace, opts v1.UpdateOptions) (*apiv1alpha1.ChainNamespace, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.ChainNamespace, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.ChainNamespaceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.ChainNamespace, err error)
	Apply(ctx context.Context, chainNamespace *applyconfigurationapiv1alpha1.ChainNamespaceApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.ChainNamespace, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, chainNamespace *applyconfigurationapiv1alpha1.ChainNamespaceApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.ChainNamespace, err error)
	ChainNamespaceExpansion
}

// chainNamespaces implements ChainNamespaceInterface
type chainNamespaces struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.ChainNamespace, *apiv1alpha1.ChainNamespaceList, *applyconfigurationapiv1alpha1.ChainNamespaceApplyConfiguration]
}

// newChainNamespaces returns a ChainNamespaces
func newChainNamespaces(c *FabricxV1alpha1Client) *chainNamespaces {
	return &chainNamespaces{
		gentype.NewClientWithListAndApply[*apiv1alpha1.ChainNamespace, *apiv1alpha1.ChainNamespaceList, *applyconfigurationapiv1alpha1.ChainNamespaceApplyConfiguration](
			"chainnamespaces",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *apiv1alpha1.ChainNamespace { return &apiv1alpha1.ChainNamespace{} },
			func() *apiv1alpha1.ChainNamespaceList { return &apiv1alpha1.ChainNamespaceList{} },
		),
	}
}
