/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/applyconfiguration/api/v1alpha1"
	scheme "github.com/kfsoftware/fabric-x-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OrdererRoutersGetter has a method to return a OrdererRouterInterface.
// A group's client should implement this interface.
type OrdererRoutersGetter interface {
	OrdererRouters(namespace string) OrdererRouterInterface
}

// OrdererRouterInterface has methods to work with OrdererRouter resources.
type OrdererRouterInterface interface {
	Create(ctx context.Context, ordererRouter *apiv1alpha1.OrdererRouter, opts v1.CreateOptions) (*apiv1alpha1.OrdererRouter, error)
	Update(ctx context.Context, ordererRouter *apiv1alpha1.OrdererRouter, opts v1.UpdateOptions) (*apiv1alpha1.OrdererRouter, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, ordererRouter *apiv1alpha1.OrdererRouter, opts v1.UpdateOptions) (*apiv1alpha1.OrdererRouter, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.OrdererRouter, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.OrdererRouterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.OrdererRouter, err error)
	Apply(ctx context.Context, ordererRouter *applyconfigurationapiv1alpha1.OrdererRouterApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.OrdererRouter, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, ordererRouter *applyconfigurationapiv1alpha1.OrdererRouterApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.OrdererRouter, err error)
	OrdererRouterExpansion
}

// ordererRouters implements OrdererRouterInterface
type ordererRouters struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.OrdererRouter, *apiv1alpha1.OrdererRouterList, *applyconfigurationapiv1alpha1.OrdererRouterApplyConfiguration]
}

// newOrdererRouters returns a OrdererRouters
func newOrdererRouters(c *ApiV1alpha1Client, namespace string) *ordererRouters {
	return &ordererRouters{
		gentype.NewClientWithListAndApply[*apiv1alpha1.OrdererRouter, *apiv1alpha1.OrdererRouterList, *applyconfigurationapiv1alpha1.OrdererRouterApplyConfiguration](
			"ordererrouters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.OrdererRouter { return &apiv1alpha1.OrdererRouter{} },
			func() *apiv1alpha1.OrdererRouterList { return &apiv1alpha1.OrdererRouterList{} },
		),
	}
}
