/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/applyconfiguration/api/v1alpha1"
	scheme "github.com/kfsoftware/fabric-x-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OrdererAssemblersGetter has a method to return a OrdererAssemblerInterface.
// A group's client should implement this interface.
type OrdererAssemblersGetter interface {
	OrdererAssemblers(namespace string) OrdererAssemblerInterface
}

// OrdererAssemblerInterface has methods to work with OrdererAssembler resources.
type OrdererAssemblerInterface interface {
	Create(ctx context.Context, ordererAssembler *apiv1alpha1.OrdererAssembler, opts v1.CreateOptions) (*apiv1alpha1.OrdererAssembler, error)
	Update(ctx context.Context, ordererAssembler *apiv1alpha1.OrdererAssembler, opts v1.UpdateOptions) (*apiv1alpha1.OrdererAssembler, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, ordererAssembler *apiv1alpha1.OrdererAssembler, opts v1.UpdateOptions) (*apiv1alpha1.OrdererAssembler, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.OrdererAssembler, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.OrdererAssemblerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.OrdererAssembler, err error)
	Apply(ctx context.Context, ordererAssembler *applyconfigurationapiv1alpha1.OrdererAssemblerApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.OrdererAssembler, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, ordererAssembler *applyconfigurationapiv1alpha1.OrdererAssemblerApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.OrdererAssembler, err error)
	OrdererAssemblerExpansion
}

// ordererAssemblers implements OrdererAssemblerInterface
type ordererAssemblers struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.OrdererAssembler, *apiv1alpha1.OrdererAssemblerList, *applyconfigurationapiv1alpha1.OrdererAssemblerApplyConfiguration]
}

// newOrdererAssemblers returns a OrdererAssemblers
func newOrdererAssemblers(c *FabricxV1alpha1Client, namespace string) *ordererAssemblers {
	return &ordererAssemblers{
		gentype.NewClientWithListAndApply[*apiv1alpha1.OrdererAssembler, *apiv1alpha1.OrdererAssemblerList, *applyconfigurationapiv1alpha1.OrdererAssemblerApplyConfiguration](
			"ordererassemblers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.OrdererAssembler { return &apiv1alpha1.OrdererAssembler{} },
			func() *apiv1alpha1.OrdererAssemblerList { return &apiv1alpha1.OrdererAssemblerList{} },
		),
	}
}
