/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	fabricxoperatorapiv1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	versioned "github.com/kfsoftware/fabric-x-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kfsoftware/fabric-x-operator/pkg/client/informers/externalversions/internalinterfaces"
	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/listers/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CAInformer provides access to a shared informer and lister for
// CAs.
type CAInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.CALister
}

type cAInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCAInformer constructs a new informer for CA type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCAInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCAInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCAInformer constructs a new informer for CA type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCAInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().CAs(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().CAs(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().CAs(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().CAs(namespace).Watch(ctx, options)
			},
		},
		&fabricxoperatorapiv1alpha1.CA{},
		resyncPeriod,
		indexers,
	)
}

func (f *cAInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCAInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cAInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&fabricxoperatorapiv1alpha1.CA{}, f.defaultInformer)
}

func (f *cAInformer) Lister() apiv1alpha1.CALister {
	return apiv1alpha1.NewCALister(f.Informer().GetIndexer())
}
