/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	fabricxoperatorapiv1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	versioned "github.com/kfsoftware/fabric-x-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kfsoftware/fabric-x-operator/pkg/client/informers/externalversions/internalinterfaces"
	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/pkg/client/listers/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ChainNamespaceInformer provides access to a shared informer and lister for
// ChainNamespaces.
type ChainNamespaceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.ChainNamespaceLister
}

type chainNamespaceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewChainNamespaceInformer constructs a new informer for ChainNamespace type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewChainNamespaceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredChainNamespaceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredChainNamespaceInformer constructs a new informer for ChainNamespace type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredChainNamespaceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FabricxV1alpha1().ChainNamespaces().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FabricxV1alpha1().ChainNamespaces().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FabricxV1alpha1().ChainNamespaces().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FabricxV1alpha1().ChainNamespaces().Watch(ctx, options)
			},
		},
		&fabricxoperatorapiv1alpha1.ChainNamespace{},
		resyncPeriod,
		indexers,
	)
}

func (f *chainNamespaceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredChainNamespaceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *chainNamespaceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&fabricxoperatorapiv1alpha1.ChainNamespace{}, f.defaultInformer)
}

func (f *chainNamespaceInformer) Lister() apiv1alpha1.ChainNamespaceLister {
	return apiv1alpha1.NewChainNamespaceLister(f.Informer().GetIndexer())
}
