/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/kfsoftware/fabric-x-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// CAs returns a CAInformer.
	CAs() CAInformer
	// CAEnrollments returns a CAEnrollmentInformer.
	CAEnrollments() CAEnrollmentInformer
	// ChainNamespaces returns a ChainNamespaceInformer.
	ChainNamespaces() ChainNamespaceInformer
	// Committers returns a CommitterInformer.
	Committers() CommitterInformer
	// Endorsers returns a EndorserInformer.
	Endorsers() EndorserInformer
	// Genesises returns a GenesisInformer.
	Genesises() GenesisInformer
	// Identities returns a IdentityInformer.
	Identities() IdentityInformer
	// OrdererAssemblers returns a OrdererAssemblerInformer.
	OrdererAssemblers() OrdererAssemblerInformer
	// OrdererBatchers returns a OrdererBatcherInformer.
	OrdererBatchers() OrdererBatcherInformer
	// OrdererConsenters returns a OrdererConsenterInformer.
	OrdererConsenters() OrdererConsenterInformer
	// OrdererGroups returns a OrdererGroupInformer.
	OrdererGroups() OrdererGroupInformer
	// OrdererRouters returns a OrdererRouterInformer.
	OrdererRouters() OrdererRouterInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// CAs returns a CAInformer.
func (v *version) CAs() CAInformer {
	return &cAInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CAEnrollments returns a CAEnrollmentInformer.
func (v *version) CAEnrollments() CAEnrollmentInformer {
	return &cAEnrollmentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ChainNamespaces returns a ChainNamespaceInformer.
func (v *version) ChainNamespaces() ChainNamespaceInformer {
	return &chainNamespaceInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Committers returns a CommitterInformer.
func (v *version) Committers() CommitterInformer {
	return &committerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Endorsers returns a EndorserInformer.
func (v *version) Endorsers() EndorserInformer {
	return &endorserInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Genesises returns a GenesisInformer.
func (v *version) Genesises() GenesisInformer {
	return &genesisInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Identities returns a IdentityInformer.
func (v *version) Identities() IdentityInformer {
	return &identityInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// OrdererAssemblers returns a OrdererAssemblerInformer.
func (v *version) OrdererAssemblers() OrdererAssemblerInformer {
	return &ordererAssemblerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// OrdererBatchers returns a OrdererBatcherInformer.
func (v *version) OrdererBatchers() OrdererBatcherInformer {
	return &ordererBatcherInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// OrdererConsenters returns a OrdererConsenterInformer.
func (v *version) OrdererConsenters() OrdererConsenterInformer {
	return &ordererConsenterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// OrdererGroups returns a OrdererGroupInformer.
func (v *version) OrdererGroups() OrdererGroupInformer {
	return &ordererGroupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// OrdererRouters returns a OrdererRouterInformer.
func (v *version) OrdererRouters() OrdererRouterInformer {
	return &ordererRouterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
