apiVersion: fabricx.kfsoft.tech/v1alpha1
kind: Committer
metadata:
  name: fabric-x-committer
  namespace: default

spec:
  bootstrapMode: deploy
  mspid: CommitterMSP
  image: hyperledger/fabric-x-committer
  imageTag: "0.1.5"
  common:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    podAnnotations:
      prometheus.io/port: "8080"
      prometheus.io/scrape: "true"
    podLabels:
      app.kubernetes.io/component: fabric-x
      app.kubernetes.io/part-of: committer
  genesis:
    secretName: fabricx-shared-genesis
    secretKey: genesis.block
    secretNamespace: default
  components:
    # Global endpoints used by sidecar and coordinator
    ordererEndpoints:
      - orderergroup-party1-consenter:7052
      - orderergroup-party2-consenter:7052
      - orderergroup-party3-consenter:7052
      - orderergroup-party4-consenter:7052
    committerHost: fabric-x-committer-coordinator-service.default.svc.cluster.local
    committerPort: 9001

    # Coordinator-specific upstream endpoints
    coordinatorVerifierEndpoints:
      - fabric-x-committer-verifier-service.default.svc.cluster.local:5001
    coordinatorValidatorCommitterEndpoints:
      - fabric-x-committer-validator-service.default.svc.cluster.local:6001
    coordinator:
      replicas: 1
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      env:
        - name: COORDINATOR_LOG_LEVEL
          value: INFO
      ingress:
        istio:
          hosts:
            - coordinator-committer.localho.st
          ingressGateway: ingressgateway
          port: 443
    sidecar:
      replicas: 1
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
        limits:
          cpu: 1500m
          memory: 2Gi
      env:
        - name: SC_SIDECAR_LOG_LEVEL
          value: DEBUG
        - name: SC_SIDECAR_ORDERER_CHANNEL_ID
          value: arma
      ingress:
        istio:
          hosts:
            - sidecar-committer.localho.st
          ingressGateway: ingressgateway
          port: 443
    validator:
      replicas: 1
      postgresql:
        host: postgresql-rw.default.svc.cluster.local
        port: 5432
        database: queryservice
        username: queryservice
        passwordSecret:
          name: postgresql-credentials
          namespace: default
          key: password
        maxConnections: 100
        minConnections: 10
        loadBalance: true
        retry:
          maxElapsedTime: 5m

      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      env:
        - name: VALIDATOR_LOG_LEVEL
          value: INFO
      ingress:
        istio:
          hosts:
            - validator-committer.localho.st
          ingressGateway: ingressgateway
          port: 443
    verifierService:
      replicas: 1
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      env:
        - name: VERIFIER_LOG_LEVEL
          value: INFO
        - name: VERIFIER_PARALLELISM
          value: "80"
      ingress:
        istio:
          hosts:
            - verifier-committer.localho.st
          ingressGateway: ingressgateway
          port: 443
    queryService:
      replicas: 1
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      env:
        - name: QUERY_SERVICE_LOG_LEVEL
          value: INFO
      command:
        - committer
      args:
        - start-query
        - --config=/config/config.yaml
      ingress:
        istio:
          hosts:
            - query-service-committer.localho.st
          ingressGateway: ingressgateway
          port: 443
      postgresql:
        host: postgresql-rw.default.svc.cluster.local
        port: 5432
        database: queryservice
        username: queryservice
        passwordSecret:
          name: postgresql-credentials
          namespace: default
          key: password
        maxConnections: 50
        minConnections: 10
        loadBalance: false
        retry:
          maxElapsedTime: 5m
  enrollment:
    sign:
      ca:
        caname: ca
        cahost: test-ca2.default
        caport: 7054
        catls:
          secretRef:
            key: tls.crt
            name: test-ca2-tls-crypto
            namespace: default
        enrollid: admin
        enrollsecret: adminpw
    tls:
      ca:
        caname: tlsca
        cahost: test-ca2.default
        caport: 7054
        catls:
          secretRef:
            key: tls.crt
            name: test-ca2-tls-crypto
            namespace: default
        enrollid: admin
        enrollsecret: adminpw
