apiVersion: fabricx.kfsoft.tech.kfsoft.tech/v1alpha1
kind: CAEnrollment
metadata:
  labels:
    app.kubernetes.io/name: fabric-x-operator
    app.kubernetes.io/managed-by: kustomize
  name: caenrollment-sample
spec:
  # TODO(user): Add fields here
