apiVersion: fabricx.kfsoft.tech/v1alpha1
kind: Endorser
metadata:
  labels:
    app.kubernetes.io/name: fabric-x-operator
    app.kubernetes.io/managed-by: kustomize
  name: org1-issuer
  namespace: default
spec:
  bootstrapMode: deploy
  mspid: Org1MSP
  image: token-sdk-issuer
  version: fabricx-latest
  command:
    - "app"
  args:
    - "--conf=/var/hyperledger/fabric/config"
    - "--port=9000"

  common:
    replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    podAnnotations:
      prometheus.io/port: "9090"
      prometheus.io/scrape: "true"
    podLabels:
      app.kubernetes.io/component: issuer
      app.kubernetes.io/part-of: fabric-x

    volumes:
      - name: data
        volumeSource:
          persistentVolumeClaim:
            claimName: org1-issuer-data
            readOnly: false
      - name: idemix-wallet
        volumeSource:
          secret:
            secretName: org1-issuer-idemix-idemix-cred
            items:
              - key: Sk
                path: keystore/priv_sk
              - key: Cred
                path: signcerts/cert.pem
      - name: sign-identity
        volumeSource:
          secret:
            secretName: org1-issuer-idemix-idemix-cred
            items:
              - key: Sk
                path: keystore/priv_sk
              - key: Sk
                path: keystore/key.pem
              - key: Cred
                path: signcerts/cert.pem
              - key: IssuerPublicKey
                path: cacerts/ca.pem

    volumeMounts:
      - name: data
        mountPath: /var/hyperledger/fabric/data
        readOnly: false
      - name: data
        mountPath: /var/hyperledger/fabric/config/data
        readOnly: false
      - name: idemix-wallet
        mountPath: /var/hyperledger/fabric/config/wallet/iss
        readOnly: true
      - name: sign-identity
        mountPath: /var/hyperledger/fabric/config/keys/fabric/user/msp
        readOnly: true

  core:
    logging:
      spec: info
      format: "%{color}%{time:15:04:05.000} [%{module}] %{shortfunc} %{level:.4s}%{color:reset} %{message}"

    fsc:
      id: issuer
      identity:
        cert:
          file: ""
        key:
          file: ""
      p2p:
        listenAddress: /ip4/0.0.0.0/tcp/9301
        type: websocket
      persistences:
        default:
          type: sqlite
          opts:
            dataSource: file:/var/hyperledger/fabric/data/fts.sqlite
      endpoint:
        resolvers:
          - name: endorser1
            identity:
              id: endorser1
              secretRef:
                name: org1-endorser1-idemix-idemix-cred
                namespace: default
                key: Cred
            addresses:
              P2P: org1-endorser1-service.default.svc.cluster.local:9301
          - name: endorser2
            identity:
              id: endorser2
              secretRef:
                name: org1-endorser2-idemix-idemix-cred
                namespace: default
                key: Cred
            addresses:
              P2P: org1-endorser2-service.default.svc.cluster.local:9301
          - name: owner1
            identity:
              id: owner1
              secretRef:
                name: org1-owner1-idemix-idemix-cred
                namespace: default
                key: Cred
            addresses:
              P2P: org1-owner1-service.default.svc.cluster.local:9301
          - name: owner2
            identity:
              id: owner2
              secretRef:
                name: org1-owner2-idemix-idemix-cred
                namespace: default
                key: Cred
            addresses:
              P2P: org1-owner2-service.default.svc.cluster.local:9301

    fabric:
      enabled: true
      default:
        driver: fabricx
        defaultMSP: user
        msps:
          - id: user
            mspType: bccsp
            mspID: Org1MSP
            path: /var/hyperledger/fabric/config/keys/fabric/user/msp
        tls:
          enabled: false
        peers:
          - address: fabric-x-committer-sidecar-service.default:5050
            usage: delivery
        queryService:
          - address: fabric-x-committer-query-service-service.default:9001
        channels:
          - name: arma
            default: true

    token:
      enabled: true
      tms:
        mytms:
          network: default
          channel: arma
          namespace: token_namespace
          driver: zkatdlog
          services:
            network:
              fabric:
                fsc_endorsement:
                  endorser: false
                  id: issuer
                  policy:
                    type: all
                  endorsers:
                    - endorser1
                    - endorser2

  enrollment:
    sign:
      ca:
        caname: idemix-ca
        cahost: endorser-idemix-ca.default
        caport: 7054
        catls:
          secretRef:
            key: tls.crt
            name: endorser-idemix-ca-tls-crypto
            namespace: default
        enrollid: issuer
        enrollsecret: issuerpw
    tls:
      ca:
        caname: tlsca
        cahost: endorser-idemix-ca.default
        caport: 7054
        catls:
          secretRef:
            key: tls.crt
            name: endorser-idemix-ca-tls-crypto
            namespace: default
        enrollid: issuer
        enrollsecret: issuerpw
      sans:
        dnsNames:
          - org1-issuer
          - org1-issuer.default
          - org1-issuer.default.svc.cluster.local
          - issuer.example.com

  ingress:
    istio:
      hosts:
        - issuer.localho.st
      ingressGateway: istio-ingressgateway
      port: 443
      tls:
        enabled: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: org1-issuer-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
