## Append samples of your project ##
resources:
- fabricx_v1alpha1_committer.yaml
- fabricx_v1alpha1_orderergroup.yaml
- fabricx_v1alpha1_endorser.yaml
- fabricx_v1alpha1_ca.yaml
- fabricx_v1alpha1_genesis.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
