/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IdentityLister helps list Identities.
// All objects returned here must be treated as read-only.
type IdentityLister interface {
	// List lists all Identities in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.Identity, err error)
	// Identities returns an object that can list and get Identities.
	Identities(namespace string) IdentityNamespaceLister
	IdentityListerExpansion
}

// identityLister implements the IdentityLister interface.
type identityLister struct {
	listers.ResourceIndexer[*apiv1alpha1.Identity]
}

// NewIdentityLister returns a new IdentityLister.
func NewIdentityLister(indexer cache.Indexer) IdentityLister {
	return &identityLister{listers.New[*apiv1alpha1.Identity](indexer, apiv1alpha1.Resource("identity"))}
}

// Identities returns an object that can list and get Identities.
func (s *identityLister) Identities(namespace string) IdentityNamespaceLister {
	return identityNamespaceLister{listers.NewNamespaced[*apiv1alpha1.Identity](s.ResourceIndexer, namespace)}
}

// IdentityNamespaceLister helps list and get Identities.
// All objects returned here must be treated as read-only.
type IdentityNamespaceLister interface {
	// List lists all Identities in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.Identity, err error)
	// Get retrieves the Identity from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.Identity, error)
	IdentityNamespaceListerExpansion
}

// identityNamespaceLister implements the IdentityNamespaceLister
// interface.
type identityNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.Identity]
}
