/*
 * Copyright kfsoft.tech. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kfsoftware/fabric-x-operator/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// OrdererAssemblerLister helps list OrdererAssemblers.
// All objects returned here must be treated as read-only.
type OrdererAssemblerLister interface {
	// List lists all OrdererAssemblers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.OrdererAssembler, err error)
	// OrdererAssemblers returns an object that can list and get OrdererAssemblers.
	OrdererAssemblers(namespace string) OrdererAssemblerNamespaceLister
	OrdererAssemblerListerExpansion
}

// ordererAssemblerLister implements the OrdererAssemblerLister interface.
type ordererAssemblerLister struct {
	listers.ResourceIndexer[*apiv1alpha1.OrdererAssembler]
}

// NewOrdererAssemblerLister returns a new OrdererAssemblerLister.
func NewOrdererAssemblerLister(indexer cache.Indexer) OrdererAssemblerLister {
	return &ordererAssemblerLister{listers.New[*apiv1alpha1.OrdererAssembler](indexer, apiv1alpha1.Resource("ordererassembler"))}
}

// OrdererAssemblers returns an object that can list and get OrdererAssemblers.
func (s *ordererAssemblerLister) OrdererAssemblers(namespace string) OrdererAssemblerNamespaceLister {
	return ordererAssemblerNamespaceLister{listers.NewNamespaced[*apiv1alpha1.OrdererAssembler](s.ResourceIndexer, namespace)}
}

// OrdererAssemblerNamespaceLister helps list and get OrdererAssemblers.
// All objects returned here must be treated as read-only.
type OrdererAssemblerNamespaceLister interface {
	// List lists all OrdererAssemblers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.OrdererAssembler, err error)
	// Get retrieves the OrdererAssembler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.OrdererAssembler, error)
	OrdererAssemblerNamespaceListerExpansion
}

// ordererAssemblerNamespaceLister implements the OrdererAssemblerNamespaceLister
// interface.
type ordererAssemblerNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.OrdererAssembler]
}
